### ISSUE TITLE
Revisions to "Translate" extension

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#1029]
## Icon
The current icon depicts a Chinese character of "文" which means "text" or "article" and is part of the official Google Translate logo (see below). Currently the rendering of this glyph is a little rough / clipped which makes the glyph difficult to read. In addition, focusing the extension on this glyph may be a little alienating to other groups in our large community which spans every part of the globe. For these reasons we should design and develop some alternatives.

![image](https://user-images.githubusercontent.com/747641/38437664-32859a2a-39a6-11e8-9080-0802823ef4e6.png)

## Additional Blocks
We would like to add the following reporter block which will provide the current language being used by the current viewer of a given project:

`viewer language` (reporter)

/cc @carljbowman @ntlrsk

**Comment by picklesrus** [comment]
For the logo, we'll probably need to circle back with the folks that Erik was talking to before.  I can dig some of the old conversations/slide decks if that's useful.

Adding some more of the TODO's I've been tracking to the list, though I can put these in a separate bug if you'd prefer.
- Allow the language menu to accept language names 
- Use the project language as the default instead of English (first step is to change to the browser language)
- Retry the supported languages request if it fails
- Set a default value in the language menu
- pick default translate text
- i18n for block text

**Comment by fsih** [comment]
Probably irrelevant, but I think it's the Japanese http://jisho.org/search/%23kanji%20%E6%96%87 which differs from Chinese (and Korean) in that it has a vertical short line at the top. (Still, it's readable in 3 Asian languages, so that might have been why they chose that glyph.)

**Comment by thisandagain** [comment]
@fsih Interesting! Thanks. It still feels a bit odd to focus on this specific for the same reason as mentioned above though.

**Comment by ntlrsk** [comment]
I encourage using a different icon for translation for the reasons @thisandagain mentioned. 

(Hard to say what variation of the character the illustrator was going for https://en.wiktionary.org/wiki/%E6%96%87   )

**Comment by Kenny2github** [comment]
I would suggest going with something similar to Wikipedia's globe:
![globe](https://en.wikipedia.org/static/images/project-logos/enwiki.png)
(of course without the wordmark)
Or maybe the Scratch Wiki's "ball of many countries" image:
![ball](https://en.scratch-wiki.info/w/images/Ball_of_many_countries.png)
I suspect that it would be easier to use the Wiki countries ball, since a) it seems to be original and b) it's public domain (I think the WP globe is copyrighted?)

**Comment by apple502j** [comment]
WP glove is trademarked & cc by-sa 3.0
Not BSD

I doubt wiki countries ball is PD. This file is copied from other website.
Many websites use that such as http://deafworldsign.com/world-travel/

And I disagree Ken's idea, even if it's without any copyright problems
I don't think this means "many languages" but "many countries".

My idea:
The glove icon which is used in language switcher in Scratch 2.0/3.0
