### ISSUE TITLE
Change default values for string operators

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-vm#1049]
The default values for the string operators are "hello" and "world." Although tradition for programming language introductions, newcomers wouldn't know that, and they don't help at all to understand what the string operators do . 

To make the function of the string operators more understandable, recommendation is to change to:

join apple banana
letter 1 of apple
length of apple
apple contains a ?

![image](https://user-images.githubusercontent.com/4721032/38640854-73062820-3da3-11e8-90bd-5e957225703c.png)

**Comment by AmazingMech2418** [comment]
I really think that the original default values for the <[] contains []?> block would confuse people new to scratch since "hello" is nowhere close to containing "world". Also, most people who haven't programmed before wouldn't know that "hello world" is something used for traditional programming introductions. They wouldn't know that the first program in a language traditionally is making something say "hello world".

**Comment by fsih** [comment]
"join apple banana" reads less like English than most Scratch blocks. Maybe it should be "join apple to banana", "join apple with banana", "join apple and banana"?

**Comment by mrjacobbloom** [comment]
>"join apple banana" reads less like English than most Scratch blocks. Maybe it should be "join apple to banana", "join apple with banana", "join apple and banana"?

I often find myself using a lot of join blocks in the same statement. The way it is now, you can set it up so that all the joined pieces of text are right next to each-other, and it feels to me like having with/to/and in the middle of the block would make that situation less readable:

![image](https://user-images.githubusercontent.com/2879020/38743210-bdba7a2a-3efb-11e8-8000-0a67bbb6814b.png)

**Comment by thisandagain** [comment]
Moved to LLK/scratch-gui#1797
