### ISSUE TITLE
About webpack packaging.

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-vm#1052]
Please comment：
I downloaded the node_modules file in the scratch-gui project and modified the scratch-vm.
The NPM run build is then executed, and the resulting dist file is found to be different from the previous one.
What's the problem? Is it because of the node version problem?? The node version is v9.9.0.
please help me, thank you!

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/26614335/38713080-f792206c-3f01-11e8-9d0e-888dfe13e3f6.png)
There will be errors when repackaging.

**Comment by thisandagain** [comment]
Hi @zwy429. We recommend using Node.js version 8 LTS. Based on that error it looks like you may be attempting to load a SB2 / SB3 file that is not valid.

**Comment by jonathanperret** [comment]
@zwy429 I hit the exact same problem when trying to rebuild `scratch-vm` for use in `scratch-gui`.

Even though I made sure to rebuild `scratch-vm` at the same commit that was used to build the working version (that was d177f4cd0c316653b83c7547c001566523d7f374), the resulting `scratch-vm.js` was very different from the npm release.

Turned out to be a dependency version issue. Because `scratch-vm`'s `package.json` referenced `scratch-parser` at the `latest` version, it was difficult to reproduce the build. I finally made it work by forcing `scratch-parser` at version `2.0.1`.

Fortunately since https://github.com/LLK/scratch-vm/commit/7fd6dca374db24d6695144f1ee6593fb311fd998#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 `scratch-parser` is pinned at a specific version so things should have a better chance of working.
