### ISSUE TITLE
Travis build failed with "Cannot find module 'scratch-audio'"

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1187]
Any ideas @rschamp?

```
1.39s$ npm run $NPM_SCRIPT
> scratch-vm@0.1.0 build /home/travis/build/LLK/scratch-vm
> webpack --progress --colors --bail
/home/travis/build/LLK/scratch-vm/node_modules/webpack-cli/bin/webpack.js:243
				throw err;
				^
Error: Cannot find module 'scratch-audio'
    at Function.Module._resolveFilename (module.js:547:15)
```

**Comment by mzgoddard** [comment]
@ericrosenbaum try dumping travis's node_modules cache?

**Comment by ericrosenbaum** [comment]
thanks @mzgoddard - that fixed it! 

@rschamp @paulkaplan maybe something to keep an eye on...

**Comment by paulkaplan** [comment]
If that has to be done every build we should disable the build cache

**Comment by mzgoddard** [comment]
@paulkaplan I believe this is from the change on how the packages expose themselves in the browser name. Mechanically scratch-vm's dependencies should have been merged and published and then scratch-vm's package.json updated to depend on those changes.

greenkeeper didn't notice the issue because it tests with fresh branches which Travis doesn't have an existing cache to rely on.

Fresh clones without existing node_modules installed would not have encountered the issue either.

This kind of thing can happen anytime scratch-vm depends on a scratch inter-package internal api change without depending on the dependencies new version. The scratch-* entrypoints count as an internal api change I think.

(I'm not sure I'm expressing this right.)

**Comment by rschamp** [comment]
I've removed all of Travis's caches to help mitigate this.
