### ISSUE TITLE
Execution order of original sprite and clones is backwards

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#1247]
### Expected Behavior
The order of execution for sprites and their clones should match Scratch 2.0

### Actual Behavior
The order of execution for sprites and their clones is the opposite of Scratch 2.0

### Reference (HT [Mr-Dave](https://scratch.mit.edu/users/Mr-Dave/))

A clone will execute events before the original sprite in Scratch 3.0 but the opposite is true for Scratch 2. [Mr-Dave](https://scratch.mit.edu/discuss/topic/299791/?page=181#post-3143035) noticed the problem in these projects:

*Tower Defense*
https://scratch.mit.edu/projects/71816138/
https://preview.scratch.mit.edu/#71816138

*Minimal Repro Case*
https://scratch.mit.edu/projects/229249805/
https://preview.scratch.mit.edu/#229249805

### Operating System and Browser
Windows 7, Firefox 60.0, Flash 30.0 (release 0)

**Comment by thisandagain** [comment]
Note: I did very little investigation here aside from repro via the projects listed. This will need a little digging.

**Comment by towerofnix** [comment]
Hat blocks are started by [`startHats`](https://github.com/LLK/scratch-vm/blob/6e2af4f3cc336d20173ab7725efc89a71cd113f4/src/engine/runtime.js#L1117-L1208), which calls [`allScriptsDo`](https://github.com/LLK/scratch-vm/blob/6e2af4f3cc336d20173ab7725efc89a71cd113f4/src/engine/runtime.js#L1094-L1115) and [pushes threads](https://github.com/LLK/scratch-vm/blob/6e2af4f3cc336d20173ab7725efc89a71cd113f4/src/engine/runtime.js#L1204-L1205) according to the order that `allScriptsDo` works.

`allScriptsDo` [loops through each of the runtime's `targets` array](https://github.com/LLK/scratch-vm/blob/6e2af4f3cc336d20173ab7725efc89a71cd113f4/src/engine/runtime.js#L1107). [`createClone`](https://github.com/LLK/scratch-vm/blob/846f2121105414bd0514f7eb0e81648f03c80ed9/src/blocks/scratch3_control.js#L147-L167) is the function for the "create clone of" block, and [it pushes clones to the runtime `targets` array](https://github.com/LLK/scratch-vm/blob/846f2121105414bd0514f7eb0e81648f03c80ed9/src/blocks/scratch3_control.js#L162-L166). This is a little bit weird, because, since it's *pushing* a target, one would expect those to be executed *after* the new targets.

~~Could it be that *all* scripts are run in backwards order, so that this isn't really an issue specific to clones/sprites? Maybe a radical idea; the code *seems* to imply this, but that doesn't necessarily mean anything.~~ [Some testing](https://llk.github.io/scratch-gui/develop/#229846017) says it's fine :P

**Comment by TheLogFather** [comment]
One of the basic issues is that Scratch 2 uses the sprite/clone layer order for execution, whereas Scratch 3 just starts up the scripts in some fixed order.

See https://github.com/LLK/scratch-vm/issues/1053

Since Scratch 2 creates clones *behind* the parent, that means a new clone's scripts get started up after the parent (unless the clone gets relayered to be in front of the parent – you can easily see this in the above minimal testcase project by inserting a "go to front" block right after the "when I start as a clone"... the behaviour will then match Scratch 3).

----

On a (somewhat) related note, something I've been wondering about is whether Scratch 3 will abandon the in-sprite script execution order that Scratch 2 uses, which is based on the layer order of the scripts themselves (i.e. within the scripting pane).

In Scratch 2, if you drag a script then it ends up in the top layer, which means it gets started up last (compared to others with the same hat block).
NOTE: this specifically refers to scripts getting *started* – any scripts that are already running are not affected by layer changes.

In Scratch 3, the execution order is fixed by the order of *creation* of the scripts.

Personally, I think the Scratch 2 behaviour can lead to some unexpected changes in project behaviour while Scratchers are creating projects (since they will very likely, at some point, drag a script to move it somewhere else within the scripting pane – and that can potentially change the execution order, which can potentially change the project behaviour).
