### ISSUE TITLE
Extensions: Internationalize the bad words filter

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-vm#1253]
The bad words filter currently used by the speech extension is English only. We need to internationalize it and use it for translate, speech to text, and text to speech.

**Comment by apple502j** [comment]
They don't seem to add Bad Word Filter in Scratch 3.0's extensions.
Just ban the projects with it, not by the extension.

**Comment by towerofnix** [comment]
@apple502j Presently the bad word filter is only [on the synthesis server](https://synthesis-service.scratch.mit.edu/synth?locale=en-US&gender=female&text=there+will+be+no+audio+here+if+the+text+contains+bad+words) (not in scratch-vm). The trouble is that it only looks for English bad words - this issue is tracking a bad word filter in other languages.

Although personally, I think it would make the most sense to only do this for the "speak" (text to speech) block, since *hearing* bad words could be especially scarring. Seeing a bad word is bad too, but there's no way to prevent it at all; it's very easy to make a costume and draw a bad word in it. (Obviously, it's also quite easy to make an audio recording and say a bad word, and this would probably have a worse effect on kids in itself, but it's especially easy to drag out a speak block and type curses into it.)

**Comment by Kenny2github** [comment]
Looking at the synthesis server, it's a bit too good at doing unrecognized words... the most common swear word is blank but prepend anything and it comes through loud and clear 😛
