### ISSUE TITLE
Investigate compatibility issues with "Test Line SpeedWay"

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#1306]
### Expected Behavior
Project should behave the same in Scratch 2.0 and 3.0

### Actual Behavior
In Scratch 3.0 the horizontal lines (pen) that are used to render the road appear offset and/or scaled differently.

#### Scratch 2.0
![image](https://user-images.githubusercontent.com/747641/42379786-e0e47632-80f9-11e8-9ad6-a8fe5cc8690f.png)
https://scratch.mit.edu/projects/225569460/#editor

#### Scratch 3.0
![image](https://user-images.githubusercontent.com/747641/42379806-f57b526e-80f9-11e8-9c37-84768a1844f0.png)
https://llk.github.io/scratch-gui/develop/#225569460

### Operating System and Browser
Mac OS 10.13.5 | Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by Mr-Dave2** [comment]
It's a very complex pen-drawn program but I think the striped effect is just the way Scratch 3 draws lines with the pen.  

I wrote a small test case based on the code in the user's program.  The program draws a set of white lines against a black background three times.  Under Scratch 2 the white section will be a solid white on the first pass.  Under Scratch 3 the section does not look solid until the third pass.

[Scratch 2 link ](https://scratch.mit.edu/projects/235770548/)
[Scratch 3 link](https://preview.scratch.mit.edu/#235770548)

I've tried this on Windows 10 under Firefox (61.0), Chrome (67.0.3396.99), and Edge (42.17134.1.0)

The solid patch of blue beneath the trees is due to the way Scratch 3 treats arguments of a repeat loop.
define DrawsegmentFull
if <(@y1) < (@y2)> then
    repeat ((((@y2) - (@y1)) + (1)) / (@Resolution))

This calculation might not be an integer.  There is an open issue on this: Repeat block treats its argument differently than in Scratch 2.0 #1083

**Comment by littlekitykat** [comment]
Your were right i changed :  repeat ((((@y2) - (@y1)) + (1)) / (@resolution))
With repeat (CEILING ((((@y2) - (@y1)) + (1)) / (@resolution))). 

And the view distance is restore. but i am not able to ajuste the Line proportion.
It perfectly works with a pen at 2 or more than 3 But it makes something really stange with pen at 1 or 3 ...

**Comment by rschamp** [comment]
Addressed in LLK/scratch-render#314
