### ISSUE TITLE
Translate extension can't be loaded when locale is Hebrew

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1390]
- Switch to Hebrew
- Try to add the translate extension, nothing happens

Alternately, If you first add the translate extension, then switch to Hebrew, the translate blocks category disappears:

![hebrew-bug](https://user-images.githubusercontent.com/567844/43096358-d920b6fa-8e86-11e8-8bd1-43afd50a9034.gif)

**Comment by ericrosenbaum** [comment]
We've noticed that, for reasons we don't understand, the list of languages provided by our scratch-translate-extension-languages module does not include hebrew, so it could be that the extension fails to load when it tries to construct its menu. But, it's puzzling that there are no console errors.

**Comment by picklesrus** [comment]
Minor update: The object returned by getInfo() looks okay to me... The menu is there and full of reasonable pairs of languages. 
Another piece of minor info: once you try and load translate, all the other extensions fail in the same silent way.

**Comment by picklesrus** [comment]
This turns out to be a problem related to the characters in the translation of the category label into Hebrew. 

Here's text that makes it fail: "message": "תרגום \"גוגל\""

The escaped quotes are confusing the category menu label - everything that comes after it in the toolbox xml definition gets cut off. 

I plugged the that message into a category name in the default toolbox in the scratch-blocks playground and it fails similarly. It seems to be a problem with the scratch-blocks toolbox category name handling escaping in RTL.  Plugging the same text into labels on blocks works fine though. 

Not sure of a way to move this to the scratch-blocks repo. Do I just open a new issue and reference this one?

**Comment by chrisgarrity** [comment]
Moved to LLK/scratch-blocks#1721
