### ISSUE TITLE
Some 2.0 Projects won't open in 3.0

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1450]
Some 2.0 projects fail to load in 3.0 giving this error:
![screen shot 2018-08-13 at 1 24 33 pm](https://user-images.githubusercontent.com/1088291/44047607-d5fc74c4-9efc-11e8-8e62-6788232d5d84.png)

219549113
`Error: Failed to load project from server [id=#219549113]: TypeError: Cannot read property 'id' of undefined`
`gui Unhandled Error: Error: Failed to load project from server [id=#219549113]: TypeError: Cannot read property 'id' of undefined`

10118230
`Error: Failed to load project from server [id=#10118230]: Connection checks failed. Input "CONDITION" connection on "control_if_else" block (id="Ems8l;|SY:7JqPGQ,DVu") expected Boolean, found String`
`gui Unhandled Error: Error: Failed to load project from server [id=#10118230]: Connection checks failed. Input "CONDITION" connection on "control_if_else" block (id="Ems8l;|SY:7JqPGQ,DVu") expected Boolean, found String`

15200040
`Error: Failed to load project from server [id=#15200040]: Error: Serialized variable type with id '5_ow%Z#Tkawli]^Gs1j/-_Level' had type list, and does not match variable field that references it: <field xmlns="http://www.w3.org/1999/xhtml" name="VARIABLE" id="5_ow%Z#Tkawli]^Gs1j/-_Level" variabletype="">_Level</field>.`
`raven.js:55 Error: Tried to serialize a variable field with no variable.
    at Object.Blockly.Xml.fieldToDomVariable_ (lib.min.js:167)
    at Object.Blockly.Xml.fieldToDom_ (lib.min.js:167)
    at Object.Blockly.Xml.allFieldsToDom_ (lib.min.js:167)
    at Object.Blockly.Xml.blockToDom (lib.min.js:167)
    at new Blockly.Events.Delete (lib.min.js:167)
    at Blockly.BlockSvg.Blockly.Block.dispose (lib.min.js:167)
    at Blockly.BlockSvg.dispose (lib.min.js:167)
    at Blockly.WorkspaceSvg.Blockly.Workspace.clear (lib.min.js:167)
    at Blockly.WorkspaceSvg.clear (lib.min.js:167)
    at Blockly.WorkspaceSvg.Blockly.Workspace.dispose (lib.min.js:167)
    at Blockly.WorkspaceSvg.dispose (lib.min.js:167)`

108641277
`raven.js:55 Error: Failed to load project from server [id=#108641277]: Error: Cannot create monitor for target that cannot be found by name`
`gui Unhandled Error: Error: Failed to load project from server [id=#108641277]: Error: Cannot create monitor for target that cannot be found by name`

**Comment by kchadha** [comment]
Some notes on the specific failures:

**ID 219549113:**
Tracking the origin for the error, it seems to be an sb2 import issue (possibly another hacked block case):
![image](https://user-images.githubusercontent.com/1786240/44156346-b5786ac8-a07d-11e8-80ac-5b1fe5fde77f.png)

Here is the custom procedure definition with the block causing the issue...
![image](https://user-images.githubusercontent.com/1786240/44157395-5826dc80-a080-11e8-828c-149cb2621430.png)

Turns out this is not  a hacked block... but rather a bug in 2.0.

Steps to repro in 2.0:
1. Create a custom procedure block (`my block`)
2. Put the caller for that block into your backpack
3. Open a new project and drag the caller out from your project (it turns into a red `undefined` block)
4. create a new custom procedure block with the same name as the original (`my block`)
5. attach the custom procedure definition hat to the undefined block
6. The project JSON for this project is broken because the opcode for the `undefined` block becomes the name of the custom procedure block itself, instead of `"call"` which is the opcode for non-broken custom procedure calls

This problem should be resolved in the sb2 importer by ignoring blocks we can't find the opcodes to, which I thought was addressed by #1254, but it turns out that #1254 does not address the case where a substack of a c block only contains undefined blocks. We should add a check for `innerBlocks` being an empty array before this line https://github.com/LLK/scratch-vm/blob/develop/src/serialization/sb2.js#L830.

**ID 10118230:**
The scratch 2.0 project has a custom procedure (see picture) with a boolean argument, but the argument is being used as a string or number reporter. 

![image](https://user-images.githubusercontent.com/1786240/44059256-c6341034-9f1e-11e8-9146-a0aa327cff02.png)

Scratch blocks fails to validate this as it expects a boolean to be plugged into the if <...> then else block but instead sees a round input (string/number reporter). This issue should be fixed in the sb2 importer. We should ensure that booleans go into boolean slots regardless of how the reporter is defined in the sb2.

The SB2 JSON for the block in question reads:

![image](https://user-images.githubusercontent.com/1786240/44059462-7a5ee8c2-9f1f-11e8-9bb6-a9fd568fcf13.png)

The `"r"` in the third element of the array starting with `"getParam"` array should read `"b"` instead indicating that the offset block is a boolean block. Instead, `"r"` indicates that it is a reporter block.

**ID 108641277**
I believe this is the same as LLK/scratch-vm#1322

**Comment by BryceLTaylor** [comment]
10118230
15200040

The above two projects appear to open in the comparison but not in the editor.

**Comment by LiFaytheGoblin** [comment]
662083

has not such a complicated/big script, still crashes.

error message:
<img width="558" alt="screen shot 2018-08-17 at 1 32 42 pm" src="https://user-images.githubusercontent.com/5471273/44280215-1170e800-a222-11e8-9a08-c939f5097acb.png">

MacOS, Chrome

**Comment by kchadha** [comment]
@LiFaytheGoblin, that project that you mentioned there is actually a Scratch 1.4 project. We don't support importing those yet.

**Comment by kchadha** [comment]
I tested all the projects mentioned in this issue, and don't get the BSOD for any of them except for the one that is a .sb file.
