### ISSUE TITLE
(Scripts with) variables with non-letter or number names don't get imported correctly

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LLK/scratch-vm#1458]
### Expected Behavior

When there is a variable in a 2.0 project with the name ", <, &, ~ and the like, it is supposed to be transferred to 3.0, especially because it is possible in the 3.0 editor to create variables with such names. Scripts, that contain these variables, should also be transferred normally.

### Actual Behavior

A variable with a name like the ones described above does not get transferred to 3.0, meaning it is not accessible in the editor to use. If a monitor for this variable is on, it is still displayed in 3.0. All scripts containing weirdly named variables will also disappear and a sprite will then not work correctly.

### Steps to Reproduce
Create a project in 2.0 with a variable with a weird name and open it in 3.0.
See project 238960387

### Operating System and Browser

Mac OS, Chrome

### To test
- what happens if the variable name contains the weird character at any place (eg. starting with it vs somewhere in the middle)
- what about lists?

@kchadha

**Comment by kchadha** [comment]
Some notes:

- only some of the variable names in 238960387 are truly failing (others are not showing up because an earlier variable name failed). These are special characters like `<` or `>` which are HTML/XML characters, `"`, and `'`
- one part of the failure is because in the sb2 importer, we construct uids for the variables in the format `{uid for target}-{name of variable}`. These IDs need to be sanitized or we need to come up with a different ID scheme for the variables (it should also be noted that the variable IDing system for sb2 import already needs to change in order to resolve #1349).
- the second part of the issue is that all blocks are serialized to XML when handing off to scratch-blocks, so user defined names (e.g. variables, lists, custom procedures) should be sanitized/escaped. This part of the issue can be fixed similar to what we did for comments in #1235

**Comment by kchadha** [comment]
Tracking in #1077
