### ISSUE TITLE
Small red dots appear on the left border of some blocks after latest update

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-vm#147]
I updated scratch-blocks with `npm update` and this happens:
![scratch blocks bug](https://cloud.githubusercontent.com/assets/19158291/18278814/b98c59e2-7453-11e6-86a6-d0495accdd85.png)
:(

**Comment by thisandagain** [comment]
Updating title to reflect issue. @dekrain please use more descriptive language and provide more info (Operating System + Version, Browser + Version) when filing issues in the future.

**Comment by dekrain** [comment]
Issues:
- ~~no input on `key pressed?` block~~
- `When key pressed` doesn't work

**Comment by tmickel** [comment]
- The red dots are actually "checkboxes" that Rachel put in - but the flyout positioning has become off from a recent scratch-blocks merge with google/blockly. That's a scratch-blocks bug, not scratch-vm.
- The input on "key pressed?" looks fine on my copy. Have you pulled and rebuilt both scratch-blocks and scratch-vm?
- I think "when key pressed" has actually been broken since its implementation. Nothing has changed that would have affected this.

**Comment by dekrain** [comment]
After last update (merge pull request), inputs fixed, and the checkboxes been before blocks, not BEHIND blocks

**Comment by tmickel** [comment]
@dekrain I'm going to move this to scratch-blocks. Thanks for the report!
