### ISSUE TITLE
Some When I receive show/hide stacks don't trigger in 3.0

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1478]
In this project the word Breathe appears and does not disappear.
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#169401431
<img width="995" alt="screen shot 2018-08-14 at 11 28 28 pm" src="https://user-images.githubusercontent.com/1088291/44130200-52ba5f26-a01a-11e8-9103-20cfaa2acdf2.png">

The project uses broadcasting for each part and for some reason that sprite doesn't trigger the `When I receive 'part 14'` stack on the sprite "Part 13 Rocks"

In this project:
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#12714608
On Level 10 the red enemy sprite never appears.
<img width="984" alt="screen shot 2018-08-14 at 11 44 20 pm" src="https://user-images.githubusercontent.com/1088291/44130522-0486fd30-a01c-11e8-8bbb-782ad446cdfd.png">

It similarly has a stack with a`When I receive 'go'` hat that never triggers.

And in this project:
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#13701368
When you win (beat the pac man level) the ghosts and the monitors don't disappear on the end screen:
<img width="993" alt="screen shot 2018-08-14 at 11 53 49 pm" src="https://user-images.githubusercontent.com/1088291/44130843-75c76358-a01d-11e8-90a8-399ab4b69eea.png">

The ghosts and Pac Man have a `When I receive 'hide'` that doesn't trigger

**Comment by BryceLTaylor** [comment]
Related to this issue: https://github.com/LLK/scratch-vm/issues/1053

Also, note this project:
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#239873312

<img width="978" alt="screen shot 2018-08-23 at 1 50 40 pm" src="https://user-images.githubusercontent.com/1088291/44542690-8ee1a000-a6db-11e8-9a96-911ec2207941.png">

**Comment by mzgoddard** [comment]
The projects in this issue have the same symptom due to 4 different bugs. In all of their cases the `when I receive` are kicking off threads.

In 169401431: Breathe does not disappear because there is a race condition in the wait blocks. There are 2 separate `when I receive` hats, the first that fires waits 0.4 seconds and then shows the Breathe text. The second `when I receive` hat hides the Breathe text. The 0.4 second timer should complete and show Breathe before the second hat executes. Instead the 0.4 second timer is firing after the second hat, causing a `hide` then a `show` to execute.

In 12714608: The target input for `getAttributeOf` blocks is `Stage` when it should be `_stage_`. So those blocks always return 0 when they need to return 11 for the stated symptom of an obstruction not appearing.

13701368 represents an unusual behaviour of Scratch 2.0. `stop all` doesn't stop all threads. It stops the active thread and then removes the current thread set from future execution. Any threads that were created before `stop all` will execute one more time before stopping, not because they are instructed to stop but because they are removed from the set of running threads. It is in fact possible for the remaining threads to create new threads that will continue to execute after that tick ends.

239873312 is due to exactly #1053.

**Comment by BryceLTaylor** [comment]
Of the originally reported issues, the "Breathe" one from project 169401431, the red sprite not appearing in project 12714608, and the ordering issue from 239873312 appear to be fixed.   The ghosts still don't disappear when you win Pac Man in project 13701368.

**Comment by ktbee** [comment]
The final broken Pac Man project in this issue (13701368) was fixed by https://github.com/LLK/scratch-vm/pull/1648 !
