### ISSUE TITLE
Missing micro:bit features

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#1525]
These are in MakeCode but not in Scratch 3.

* (temperature)
* (compass)
* (acceleration)
* (magnetic force)
* plot/unplot () () - It's so hard to make a binary number just for flashing ONE CELL.
* (point () ())
* set brightness ()
* (brightness)

### Steps to Reproduce
Open MakeCode https://makecode.microbit.org/ and Scratch 3.0 with micro:bit extension.

### Operating System and Browser
any, since the code says.

**Comment by ericrosenbaum** [comment]
Thanks for the suggestions @apple502j! We try to keep Scratch extensions balanced between simplicity and power, and that's how we arrived at the set of micro:bit features we currently have.

**Comment by chewi** [comment]
Sorry to drag this up but I need to express how I'm feeling about this. I was really excited to check out Scratch 3 for the first time and find that you can work with the micro:bit without it being tethered via USB like it was in Scratch 2. I was then so disappointed to find it only supports a tiny number of features. I was looking forward to driving my Kitronik servo motors. :disappointed:

Scratch should be filling a gap left by MakeCode. With MakeCode, you can only write code for the micro:bit itself, which can be quite limiting. Pairing it with Scratch allows so much more potential. I tried to use MIT's App Inventor to fill this gap but it's nowhere near as good as Scratch. There are possibly other options but I need something my daughter will be able to cope with.

Now I would help to make this happen but extending Scratch 3 seems non-trivial and hardly worth the effort when using a custom extension means either running it from a development environment or otherwise running it from your own server.

**Comment by DaniloJust** [comment]
Hello, I agree with chewi. We would get so much options for creative applications when we can combine more sensors of the micro:bit hardware and scratch. Can we somehow help to extend the extension?
