### ISSUE TITLE
Enforce clone limit

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#159]
Scratch 2.0 enforces a limit of 300 (301) clones.

**Comment by mrjacobbloom** [comment]
if performance is better in Scratch 3, would there be any possibility of raising the limit?

**Comment by jeandrek** [comment]
Is it 300 or 301?

**Comment by tmickel** [comment]
Closing since this is now part of #150/#113. 

The current limit looks to be 300: https://github.com/LLK/scratch-flash/blob/5cff62b909856b7d7b3d116a5dcc2b4f03de8482/src/primitives/Primitives.as#L35.

Regarding raising the limit: there's a chance Scratch 3.0 will perform better with many clones. There's also a chance it won't. If it does, we may consider raising the limit. But, there may also be some non-technical reasons to have the limit be at a fathomable/not-too-large number. And, currently some projects likely depend on it. Changing the limit could affect compatibility, which we're trying to be very aware of.
