### ISSUE TITLE
Consider adding a way to detect that wedo2 has disconnected? 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1590]
We should consider whether to add a way to detect that a wedo2 has become disconnected (e.g. because the peripheral has gone out of range, or the battery has died or been removed). One way would be to send a request at some interval (e.g. to check the battery level), which would error in those cases.

**Comment by ericrosenbaum** [comment]
or: maybe Scratch Link can handle this (and we could remove the corresponding timeout check for microbit)

**Comment by evhan55** [comment]
This is especially important for macOS because it seems on Windows the WeDo2 disconnect is detected (?), but not on macOS.

Oh macOS, one way to 'test' if you are still connected to a WeDo2 is to run a `set light to n` block, because it will then detect that the WeDo2 is unresponsive and trigger an alert and show the orange status button.  However, if you try to 'test' with a motor block with no motors ever connected, it won't detect that the WeDo2 is unresponsive because we don't attempt to communicate via Scratch Link on motor blocks if no motor blocks were recently connected.
