### ISSUE TITLE
Kitten doesn't work in Japanese

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#1679]
### Expected Behavior
With these blocks Scratch should speak "meow".
![image](https://user-images.githubusercontent.com/33279053/47206051-ab8c1280-d3c2-11e8-9dcf-7c23ea21dff0.png)

### Actual Behavior
It just says "こんにちは".

### Steps to Reproduce
Load TTS Extension and add those blocks.
`こんにちは`

### Operating System and Browser
On Windows 10 Firefox 62

**Comment by towerofnix** [comment]
The cause of this issue is [this line](https://github.com/LLK/scratch-vm/blob/204dc96b2fbc9475da320e1d357ab3be852d1fac/src/extensions/scratch3_text2speech/index.js#L468), which doesn't work with Japanese text.

There [are](https://gist.github.com/ryanmcgrath/982242) [ways](http://www.localizingjapan.com/blog/2012/01/20/regular-expressions-for-japanese-text/) to make a regex match Japanese letters, but maybe it would be simpler to just split along whitespace? Ala `string.split(/\s+/).fill('meow').join(' ')` (although I definitely haven't tested that code).

**Comment by apple502j** [comment]
@towerofnix  Splitting by white space doesn't work in Japanese either, since JA does not use white space to divide words. We have to check by length of the string.

**Comment by joker314** [comment]
Is the source code for the synthesis server publicly available, out of interest?

**Comment by thisandagain** [comment]
@joker314 It is not.

**Comment by fsih** [comment]
@ericrosenbaum It might make sense to have different treatment for each language for meow? Different languages seem to say different punctuation marks (like Italian saying "semicolon"), and that way you could adapt for whether a language uses spaces, and translate "meow"
