### ISSUE TITLE
[sb2 loader] Multiple scripts

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-vm#169]
Try to load project #118312077 (don't browse, just look). This project has some scripts on one sprite, but in playground, it's only one!

**Comment by tmickel** [comment]
The problem is actually this block:
<img width="164" alt="screen shot 2016-09-12 at 2 32 14 pm" src="https://cloud.githubusercontent.com/assets/120403/18447685/baaf04a4-78f5-11e6-9cbe-51af385af9a9.png">
So far scratch-blocks has the block like this:
<img width="227" alt="screen shot 2016-09-12 at 2 32 53 pm" src="https://cloud.githubusercontent.com/assets/120403/18447720/d5e45648-78f5-11e6-885c-ede09b3399c4.png">
But there are connected blocks to the bottom of it, causing an error. Then the rest of the scripts don't load.

**Comment by tmickel** [comment]
Moved here: https://github.com/LLK/scratch-blocks/issues/592

**Comment by dekrain** [comment]
So scripts `init listeners` and `sprite clicked` don't loaded b/c of this, but `game over` by cloud variable?

**Comment by tmickel** [comment]
Once "stop other scripts in this sprite" is reached by scratch-blocks, it stops loading other blocks.
