### ISSUE TITLE
When reconnecting to EV3, I got "Oops, looks like something went wrong"

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1744]
With this console error: 

```
Uncaught TypeError: Cannot read property 'reject' of undefined
    at BT._handleResponse (lib.min.js:253740)
    at BT._handleMessage (lib.min.js:253711)
    at BT._onSocketMessage (lib.min.js:253590)
    at WebSocket.JSONRPCWebSocket._this._ws.onmessage (lib.min.js:253551)
```

I was able to recover by clicking "try again," and successfully connected.

**Comment by ericrosenbaum** [comment]
cc @evhan55 @cwillisf

**Comment by evhan55** [comment]
@ericrosenbaum  Do you remember the STR by any chance?  Also, was this only Windows?

**Comment by ericrosenbaum** [comment]
I don't have the steps to repro for this one, sorry. It was on Windows. It definitely occurred after disconnecting though, so it could be related to the Scratch Link crashes I was seeing. Not sure.

**Comment by evhan55** [comment]
We are thinking this was Windows 1803

**Comment by evhan55** [comment]
I believe this is *probably* fixed by this merged PR: https://github.com/LLK/scratch-vm/pull/1781
The error Eric was seeing here in `BT._handleResponse` seems to be the same error that is now safeguarded in that PR.  I will close this for now and we can reopen if someone runs into this again with the EV3.
