### ISSUE TITLE
Clones inherit "For this sprite only" list

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#1798]
### Expected Behavior
Like variables are, "for this sprite only" lists should be independent on each clone.

### Actual Behavior
They share the same list.

### Steps to Reproduce
I made a simple project to test it. 
![image](https://user-images.githubusercontent.com/33279053/49365536-6c274480-f72a-11e8-9768-da61622969ad.png)
[LocalListBug.zip](https://github.com/LLK/scratch-vm/files/2638846/LocalListBug.zip)
(This is a sb3 file. Change extension to `sb3`. )
Press space key. On Scratch 2.0, the parent always says "0".
On Scratch 3.0, both the parent and the clone say the same number.

### Operating System and Browser
Windows 7 / Firefox 63

Thanks to videobob for [finding this strange bug](https://scratch.mit.edu/discuss/post/3333723/)!

**Comment by Mr-Dave2** [comment]
Just wanted to add a couple of things:

The videobob's problem program is here: https://scratch.mit.edu/projects/204520399/
It fails under the Current Scratch 3.0: https://llk.github.io/scratch-gui/develop/#204520399
It Works under an older Scratch 3.0: https://llk.github.io/scratch-gui/polly/#204520399

I made another case study: Scratch 2 link: https://scratch.mit.edu/projects/263635669
Fails under current Scratch 3.0: https://llk.github.io/scratch-gui/develop/#263635669
Works under an Older Scratch 3.0:  https://llk.github.io/scratch-gui/polly/#263635669

To use my case study: Click the GF. Press Space to add "Cat" to the local list for only the Clone.  In the current Scratch 3, both local lists will be modified but the local list of the original sprite will 'lag behind' one cat (which is expected because the original sprite executes the "when space pressed" event before the clone does).

Windows 10 / FF: 63.0.3 (64-bit)

**Comment by gabrielcbe** [comment]
IDK if I should post this here or open a new one, I had a similar problem with the variables inheriting the variables from other sprites  even after creating them as "For this sprite only".

**Comment by Mr-Dave2** [comment]
Just a nit about the title.  "Clones inherit "For this sprite only" list" could be taken to describe what they are supposed to do.  It's immediately clear what you meant from your expected behavior text so perhaps, just for the sake of clarity, that could be the title? ("for this sprite only" lists should be independent on each clone).
