### ISSUE TITLE
Kitten 'meow' for Danish, Dutch and Icelandic doesn't sound right.

### ISSUE THREAD

**Issue by knandersen** [LLK/scratch-vm#1858]
### Expected Behavior

With the Text-to-Speech extension, using the Kitten voice in Danish, Dutch, and Icelandic, the 'meow' doesn't sound right.

### Actual Behavior

In Danish, the meow sounds more like 'me-u' and feels truncated.
In Dutch, the meow sounds more like 'me-um'.
In Icelandic, the meow sounds more like 'me-uf'.

For an example of how 'meow' is pronounced in Danish, see: https://youtu.be/uxiXcAioZQc?t=5
The Google Translate-version of meows are also pretty good for reference: https://translate.google.com/#view=home&op=translate&sl=auto&tl=da&text=meow

### Steps to Reproduce

1. Load TTS-extension
2. Set voice to Kitten
3. Set language to Danish, Dutch or Icelandic.
4. Say any word

**Comment by ericrosenbaum** [comment]
Thanks @knandersen! I guess our options include:

A) Always use the english female voice for kitten, so it sounds the same for everybody
B) Use the language setting, and also localize the word "meow" for that language.

At first glance, B seems better. But the localization part is tricky because we'd need to use the extension's language setting to select the word, not the editor's language setting (which is what normally controls localization). I'm not sure how to do that. Also, because the speech synthesis voices vary in quality, even if we send a localized version of the word (e.g. in Dutch, "mauw"), it may not sound much better.

**Comment by apple502j** [comment]
See also: #1702
