### ISSUE TITLE
Remove memoize

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#2]

**Comment by tmickel** [comment]
I'd like to better understand what memoization does for us here. Mostly every time we add a new block it will have a new ID, I think, making the memoization not really help. I think it should save some CPU for undo/redo but at a cost of quite a bit of keeping XML trees around in memory?

**Comment by thisandagain** [comment]
After looking at this more deeply I agree. I think we should pull it.

**Comment by tmickel** [comment]
P.S. I think the introduction of the WebWorker makes us need the htmlparser. Because the XML object passed along by Blockly isn't serializable (? - although I haven't fully investigated this exactly), I passed through the XML string instead whiich is parsed inside the worker using your implementation. The memoize, though, I think we still don't need :)
