### ISSUE TITLE
Can I test horizontal blocks yet ?

### ISSUE THREAD

**Issue by rhulha** [LLK/scratch-vm#201]
I ran StartServerWindows.bat and could play around with the vertical blocks using http://localhost:8080.
However I did not see a way to test the horizontal blocks.
Are they available yet ?

**Comment by tmickel** [comment]
We don't currently have scratch-vm operating with horizontal blocks. You can test the horizontal blocks in the scratch-blocks package (open tests/horizontal_playground.html). You could also modify the VM playground to use the horizontal blocks (switch the script includes to blockly_compressed_horizontal, blocks_compressed_horizontal, and then update the XML toolbox). The VM should operate perfectly well on horizontal blocks since the data model is the same. But, we're not actively working on that, yet as we're focused on the vertical for the moment.
