### ISSUE TITLE
Timing (setInterval, rAF, etc.)

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#208]
Currently there's a weird mix between the two... doing rAF for renderer draw calls, but using setInterval(tick) to run the scripts. This can't be right...

Which way should we use? Would be nice to think about the timing of each one and what the difference will be in practice, unless anyone already has :)

**Comment by towerofnix** [comment]
I dunno, rAF is literally "request animation frame" so it makes sense for a renderer, and it does make sense for running a block on a tick-based interval to use `setInterval` (since that's exactly what setting an interval is for)..

**Comment by mrjacobbloom** [comment]
The VM has a flag that tells the renderer whether or not to update, right?  In that case, I agree with @liam4, the current mix of rAF and setInterval is probably the "most correct" solution.

**Comment by tmickel** [comment]
To me while it seems logically "most correct" based on what these are literally supposed to be for, I'm not sure if it makes most sense in practice or not.

Since JS and the browser are sharing a single thread of execution, if we had two timers - one running in rAF and one running in setInterval, they are actually competing for the same time. But in every situation (I think) we'll want to run Scratch threads and then update the rendered display; there's no reason for there to be two separate timers (I think).

Although this doesn't talk about rAF, I think it's also relevant: http://ejohn.org/blog/how-javascript-timers-work/

**Comment by tmickel** [comment]
For example - if you create a project with a sprite that does "forever turn 1 degrees", in the current version there appears to be a motion stutter every half second or so. If I had to guess I would think this is because the `setInterval` timer becomes misaligned with the renderer's/browser's drawing; the setInterval timer might fire twice before the renderer can draw, for example, which would cause the sprite to appear to turn two degrees in one frame instead of once.

Moving everything to `requestAnimationFrame` actually makes the rotation smooth. But I wonder if that could cause compatibility problems across devices, since the rate it fires is dependent on screen refresh rate.....

**Comment by mrjacobbloom** [comment]
What if you ran the vm code a varying number of times in rAF to accommodate different framerates?

**Comment by cwillisf** [comment]
The advice I usually see for games is that `requestAnimationFrame` should be used to present the next frame of graphics but all other work should be done in other places, such as `setInterval`. That's the inspiration for way `scratch-render` is set up right now, though it's sort of a quick first-pass implementation of that idea. Of course, Scratch is a little different from most games, so it might be better to set it up differently. That's especially true now that the VM and the renderer are operating in sync with each other.

I've also seen an alternative recommendation to do as much work as possible with `requestAnimationFrame`. I think this mostly comes from wanting to avoid the possibility that work outside rAF takes too long without yielding, which would cause rAF callbacks to get missed. It seems to me that doing a lot of work without yielding (or workers) is going to interrupt smooth animation no matter what you do, so I'm not sure I buy into this advice. There may be some wisdom there that I don't yet understand, though.

I see what you mean about the stutter, @tmickel, as well as the possible problems with depending on the screen's refresh rate. My initial feeling is that we can fix the timing problems by either triple-buffering the stage or abandoning `requestAnimationFrame` entirely, but I'd like to spend some time at a whiteboard to verify.

I'd also like to better understand what does and doesn't cause tearing in WebGL, since that's one of the specific advantages of `requestAnimationFrame`. For example, if we do all of our work in a `requestAnimationFrame` callback but we do the rendering part of the work first, and the rendering part of the work takes less than 1/60th of a second, does that guarantee that we won't ever see tearing on a 60 Hz display?

**Comment by tmickel** [comment]
Here is an added complication: apparently browsers limit even `setInterval` to something like 1FPS when the tab is hidden.

That might seem fine at the surface, but I think it means threads with loops - that yield for the tick to allow a redraw - will run much slower than other threads (since ticks happen much less frequently).

Not sure how to address this...

**Comment by tmickel** [comment]
Maybe, for example, we could detect when this happens and put the project in turbo mode. But that might have other weird implications, haven't thought it through.

**Comment by mrjacobbloom** [comment]
If it helps, there's an API for detecting whether the tab is visible and firing events when that changes: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Comment by cwillisf** [comment]
I imagine our timers could report arbitrarily long pauses in at least two cases: when a computer goes to sleep or when a phone or tablet switches applications. I don't think we should try to make up for the gap in time; I think we should just take it as a frame that took a REALLY long time to render (or whatever) and do our best to keep calm and carry on.

By extension, I think it's fine to not have special handling for the "browser tab is hidden" case... though I'll admit I'm less confident in this declaration than the one above. If we do nothing, I think the hidden tab case will look similar to the case where the system is extremely busy and Scratch isn't getting much CPU time. I think if projects' timing goes a little funny in these very-low-framerate cases it's probably OK, so long as we don't crash or hang or play 1000 sounds at once.

**Comment by tmickel** [comment]
Closing for now as I took the suggestion of @cwillisf and just used `setInterval` for everything. It seems to work pretty well. We should probably continue the discussion about the above ideas and tab-backgrounding issues at some point...
