### ISSUE TITLE
BOOST extension: "when color seen" hat not working

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#2091]
The "when color seen" hat does not seem to trigger at all. I know this was working at some point! maybe the code just got out of sync.  

In general, it looks like some cleanup may be needed in how color is represented in the code, to help distinguish between the numeric values reported by the sensor, the values used internally in the menu, the localized names used on the menu, and the localized names reported by the reporter.

I would also suggest renaming the `_colorBucket` data structure, since we are using a "token bucket" in the rate limiter which is quite different- this approach seems more like a sliding window? but it could just be called `_colorSamples` or `_colorArray`.

**Comment by evhan55** [comment]
oooh `colorBucket` rename idea sounds good

**Comment by knandersen** [comment]
Yeah I agree about the renaming (addressed in https://github.com/LLK/scratch-vm/pull/2096), and that a cleanup between numeric and string representation could be useful.

The hat-block works for me though! @ericrosenbaum can you give me steps to repro? If it still doesn't work, can you check and see if the reporter works? just to see if it's the entire sensor not working for you.

I do get some false positives for `black` (kinda considering if we should remove that color all together, thoughts?).

**Comment by evhan55** [comment]
Here is a video of me testing it yesterday showing some instability:
https://photos.app.goo.gl/qzp2RYTW2RJmDdjz8

And here is a photo of a red candle next to a red LEGO brick, the red candle never reported `red`:
![img_20190405_164606_1024](https://user-images.githubusercontent.com/699840/55671406-b72ea100-585d-11e9-853a-64bdc16366ca.jpg)

Talking with @knandersen, he believes this may be best case scenario but I will let him explain more.

**Comment by evhan55** [comment]
@knandersen Said he will take this on so I will assign to him.  Please feel free to reassign to me if you'd like me to take it on instead.

**Comment by knandersen** [comment]
@ericrosenbaum @evhan55 

Just a few notes about the sensor:

- It is designed to detect certain LEGO bricks (shiny plastic): Bright Red, Blue, Dark Green, Yellow, White, and Black. 
- Its range is somewhere between 5-15mm.

After having tested the sensor this morning I feel like it's actually performing as well as I would ever expect it to. I do however feel like I'm biased when testing the sensor, because I know how to use it 'properly', but others naturally may expect it to perform differently.

I'd like to have a discussion (including some hands-on demo) around this, because I do see some things we could do. Examples:
- Rename block from `when [COLOR] color seen` to `when [COLOR] *brick* seen`, to clarify that it's optimized for LEGO bricks.
- Keep working to optimize the sensor stability (although I honestly don't think there's much to gain)
- If we're not happy with the performance, drop the sensor and use it's distance-sensing capabilities instead.

**Comment by ericrosenbaum** [comment]
Just a detail here: this is not so obvious, but hat block opcodes should never have side effects. I noticed that the `ANY` case for the `when color` opcode sets the `previousColor` [here](https://github.com/LLK/scratch-vm/blob/f02433510a14fbabcf5bc0b1ba609c7adb3b9e9a/src/extensions/scratch3_boost/index.js#L1932). The reason this is not okay is that, as soon as you have more than one hat block of that type, the second one will not work (the first one will have have already set `previousColor`, so the second one will have a different result).
