### ISSUE TITLE
BOOST extension: should "set motor speed" block yield for a tick?

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#2108]
### Expected Behavior

I expected to be able to use a stack like this to smoothly ramp the motor speed up and down:

![Screen Shot 2019-04-09 at 5 56 48 PM](https://user-images.githubusercontent.com/567844/55837960-e14bc180-5af0-11e9-903f-20879c21151a.png)

### Actual Behavior

The stack above produces an erratic behavior, because none of the blocks yield, so they run at thousands of blocks per sec, instead of the expected 30/sec.

I was able to get the desired buttery-smooth speed ramping behavior using this stack (the "set y" block yields for a tick because of the need for redraw, but I could have used e.g. "wait 0", or any other yielding block): 

![Screen Shot 2019-04-09 at 5 55 03 PM](https://user-images.githubusercontent.com/567844/55838013-0b9d7f00-5af1-11e9-8748-5558186f7cad.png)

This suggests to me that it would be helpful if this opcode yielded for a tick (e.g. using `return Promise.resolve();`). There may be some scenario where this is not desirable though? We should discuss.

**Comment by towerofnix** [comment]
>There may be some scenario where this is not desirable though?

It's worth noting (and re-noting) that, in most cases where you wouldn't want a block to yield, you can simply place it (or rather the containing loop) inside a "run without screen refresh" custom block. (I'm curious if anyone knows when that *wouldn't* be a solution, although that's only a halfway related discussion..!)

**Comment by apple502j** [comment]
@towerofnix that's right, as griffpatch said in #2079 (at least for volume block) forcing yield always pauses even inside "run without refresh".

**Comment by towerofnix** [comment]
@apple502j Oh, I see. That behavior is wonky, yeah. This comment is especially relevant: https://github.com/LLK/scratch-vm/issues/2079#issuecomment-480543599.

I did a little research and it looks like there are two kinds of "yieldiness" in Scratch 3.0:

* `return Promise.resolve()` - Yield *now*. The entire script will immediately pause, no matter what. This is the same as calling `util.yield()` (which is the reason [the "wait" block always](https://github.com/LLK/scratch-vm/blob/3d74bbd82301871ba8475540850fb3de709cc059/src/blocks/scratch3_control.js#L110-L120) yields, even if the time given is zero).
* `runtime.requestRedraw()` - Mark that this frame is "dirty", and yield at the next appropriate point (i.e. at the end of the current loop iteration). This is what the motion blocks do (as a result of calling `setXY`, `setDirection`, etc).

(It's also worth noting that turbo mode prevents making `requestRedraw` wait a frame when it otherwise would, whereas `return Promise.resolve()` will always yield a tick. It seems to be the same inside a "run without screen refresh" custom block, since "set volume" yields even then.)

I would suspect that what is wanted here is `runtime.requestRedraw()`, not `return Promise.resolve()`. That way turbo mode prevents it from yielding, which is what any user would probably expect - that is, to make the real-world results change faster (/instantaneously). It would also make "run without screen refresh" work as expected.

**Comment by ericrosenbaum** [comment]
Thanks for your comments folks. For this case, in which the block can trigger sending bluetooth messages as a side effect, I think we do want to prevent turbo mode (or run w/o screen refresh) from preventing the yield, because the bluetooth communication process would not be able to keep up with the VM's maximum speed (i.e. the radio waves themselves are fast lol, but there are bottlenecks potentially in the browser's websocket, in scratch link, in the operating system's bluetooth stack, in the computer's bluetooth hardware, and in the peripheral device's bluetooth hardware and firmware...). We are using a rate limiter in the VM here, which starts dropping messages above a certain rate- but the results of trying to send too fast and dropping most of the messages are more confusing than simply making sure the block always yields.

**Comment by towerofnix** [comment]
@ericrosenbaum Thanks for this discussion! Why drop messages when we could simply use the most recent message? For example, suppose we have this script:

    set motor speed to 10
    set motor speed to 0
    set motor speed to 30
    set motor speed to 50

If these all run instantaneously (which we'll take as given here), then Scratch will yield once, after the set-to-50 block. If we use a "drop messages past rate limit" system, and we limit to 3 messages within a short time (for example), then the final message which would have been accepted would be the set-to-30 one. The set-to-50 one would be dropped. That *would* definitely be confusing to users. (Especially if it were something like set-to-0 instead of set-to-50!) However, we don't *need* to send all those messages. If they all happen within a single instant, then *we only care about the final set value*, which is 50. So at the end of the frame, immediately before yielding but after executing any blocks, we send that one message - the one setting it to 50. And by only sending a single message per frame, we would inherently abolish the issue of sending many messages! Thoughts?
