### ISSUE TITLE
BOOST extension: setting speed continuously interferes with "turn for rotations"

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#2125]
### Expected Behavior

Setting the BOOST motor speed continuously in a loop should not interfere with the functionality of other blocks.

### Actual Behavior

If you run a stack that sets the motor speed in a loop, and then click the "turn motor for 1 rotation" block, the motor turns one rotation and then freaks out, rapidly jittering for up to several seconds. 

### Steps to Reproduce

Click the top stack to start the loop, then click the "turn motor for rotations" block:

![Screen Shot 2019-04-19 at 3 56 24 PM](https://user-images.githubusercontent.com/567844/56441624-b9601900-62bb-11e9-910d-120840836d3f.png)

A more typical case, where the speed is being changed:

<img width="346" alt="Screen Shot 2019-04-22 at 4 11 50 PM" src="https://user-images.githubusercontent.com/699840/56525725-61265280-6519-11e9-804b-7f54cf11e133.png">

**Comment by ericrosenbaum** [comment]
I looked into this a bit- there might be an error in the calculation for remaining rotations to turn, when restarting the turnOnForDegrees command after setting the power. 

Also, there's definitely a copy paste error in there- it appears the `false` used as a second argument to `Math.abs` (which makes no sense) was meant for the line below, as an argument to `turnOnForDegrees` (which would disable resetState, as is being done in other branches of the same switch)... I don't understand the resetState idea well enough to know if that is related to the bug or not.

**Comment by ericrosenbaum** [comment]
@knandersen I know you're busy with other things but any ideas on this one?

**Comment by evhan55** [comment]
There is a quick fix at #2133, not sure if it is ideal but it seems to work for the STR above at various power settings.

**Comment by knandersen** [comment]
I think you're onto something with the copy/paste-error @ericrosenbaum, and I suspect that may actually be the root cause. Because as a result, right now `setMotorPower()` incorrectly changes the `BoostMotor.state`! I can write a fix and test tomorrow!

**Comment by knandersen** [comment]
@ericrosenbaum Hmm, this is an interesting problem. Because the Boost hub firmware doesn't have a command to change the properties (speed, power, direction) of an active command, when changing properties in scratch, we use `scratch-vm` to execute a new motor-command with our best guess for how much rotation/time is/was left when the change occurred. Because rotation-based commands are calculated and regulated inside the Boost hub firmware by calculating motor-speed versus the position of the motor in a PID-loop, what I suspect is happening is that each new motor command triggered by `setMotorPower()` is causing the motors to spin up and down (jitter) to try and regulate the movement. If you try the example above with `turn for X seconds`, you don't see jittering.

Unfortunately that may mean there's no solution for this issue, because there's no way we can prevent the motors from regulating themselves. The solution @evhan55 has proposed in #2133 will fix it for speed changes that don't introduce a new speed, but as she points out, not for speeds that actually change. 😟

**Comment by ericrosenbaum** [comment]
Based on our discussion last week, the new plan is to make the "set speed" and "set direction" blocks not dynamically update an ongoing rotations command. They should still set the internal state so that the next rotations command reflects the change.
