### ISSUE TITLE
Set Tempo does not work for values under 20

### ISSUE THREAD

**Issue by ErikMejerHansen** [LLK/scratch-vm#2178]
### Expected Behavior

Setting the tempo to 10 should produce a slower drum beat than setting tempo to 20.

### Actual Behavior

Setting tempo to value below 20 has the same effect as setting the tempo to 20. 

### Steps to Reproduce
Create a program where you set the tempo to a value below 20. 
Then compare to the same program where the value is set to 20. 
![image](https://user-images.githubusercontent.com/620837/58176374-6d313b80-7ca2-11e9-9f60-c4023c824381.png)

### Operating System and Browser

macOS 10.14.1, Chrome 74.0.3729.157 (Official Build) (64-bit)

**Comment by ericrosenbaum** [comment]
We clamp the tempo range from 20 to 500 bpm [here](https://github.com/LLK/scratch-vm/blob/d2f0cf5caf6153a38da3827a4640ecf76c299547/src/extensions/scratch3_music/index.js#L711), so this is expected behavior. 

It's a compatibility feature, because Scratch 2.0 does the same thing [here](https://github.com/LLK/scratch-flash/blob/646523e6846ad0dd993213a38b46fe2ea511d026/src/scratch/ScratchStage.as#L92)
