### ISSUE TITLE
When variable changed by slider,how to trigger the change event to the stage?

### ISSUE THREAD

**Issue by alexwenbj** [LLK/scratch-vm#2287]
I want to define my own player,and meet this problem about variable show and change.
For example,I defined a global variable name "num",it can be changed by the slider, another sprite( will say the "num" value.When I change the "num",how can I inform the sprite to say this new value?（Generally speaking,I want to inform all the cases related to this variable, here just for example)

<img width="222" alt="屏幕快照 2019-10-01 下午10 54 08" src="https://user-images.githubusercontent.com/12047524/65973978-c30ebf00-e49e-11e9-8568-fd94692a9c09.png">

**Comment by SheepTester** [comment]
Assuming you have access to `vm` and know the `targetId` and `variableId` of the variable,
```js
// helper function, from somewhere in scratch-gui's code I think
// gets the variable object from the VM
const getVariable = (targetId, variableId) => {
    const target = targetId ?
        vm.runtime.getTargetById(targetId) :
        vm.runtime.getTargetForStage();
    return target.variables[variableId];
};

// when slider is changed
// sets value of the variable object from the VM to the slider value
getVariable(targetId, variableId).value = sliderValue;
```
It seems you want to play a project without using scratch-gui, but you'll still need to make some GUI elements by listening and posting to the VM since they don't come with the VM; I've tried to do this before [here](https://github.com/SheepTester/words-go-here/blob/master/htmlifier/template.html) if you want a reference

**Comment by alexwenbj** [comment]
@SheepTester Yeah,As you said,I want to play project without scratch-gui. I can get the variable changed by slider, but I CAN NOT let the related sprites response this change, for example, for most simple example,just let a sprite say the variable.I will take a look your implement for some reference.Thank you very much.
