### ISSUE TITLE
Timer.relativeTime is unused

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#2401]
[Timer.relativeTime](https://github.com/LLK/scratch-vm/blob/develop/src/util/timer.js#L78) is not used [anywhere](https://github.com/LLK/scratch-vm/search?q=relativetime&unscoped_q=relativetime) (except for test mocks). Also, this code is the same as `Timer.time` 😛 

We should remove unnecessary code to make files smaller.

**Comment by adroitwhiz** [comment]
Looks like this was introduced in https://github.com/LLK/scratch-vm/pull/410.

**Comment by AlexisGoodfellow** [comment]
Hi! I've been looking over the codebase to get a lay-of-the-land and see if there's any low-hanging fruit I could help with. It looks like this issue is fixed by an open PR (#2416) that is approved to merge and has been for many months. 

I took a brief look over the codebase with a good-ol' `grep -r` to see if there's been any changes or newly introduced usages of the `relativeTime` function - so far as `grep` reports, there haven't been any. I merged in the diff from the PR to my local branch to check it out, and all the tests are still passing.

From an outsider's perspective, I don't see anything objectionable about merging this in. I don't have write permissions on this repo though, so I'll leave it up to all of your discretion whether to merge #2146 and close this issue
