### ISSUE TITLE
Modding text strings by numbers returns 0

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-vm#2554]
### Expected Behavior

NaN should be returned when trying to mod text by numbers.

### Actual Behavior

Text strings return 0 when modded by numbers.

### Steps to Reproduce

Try to mod a text string by a number.

### Operating System and Browser

Chrome Version 84.0.4147.125 (Official Build) (64-bit), Windows 10 and [possibly others](https://scratch.mit.edu/projects/393758715/#comments-143057891).

**Comment by towerofnix** [comment]
I think it's worth discussing the context around this idea before deciding to implement it.

First off, there's a fair bit of discussion about NaN already in issue #234, though all there is a few years old by this point.

As far as this issue goes, I wonder what other blocks return NaN in Scratch 3.0? The only example that comes to mind is "sqrt (-1)", which is pretty inaccessible. Exposing the arbitrary value NaN more easily may be confusing to unfamiliar users.

Also, 3.0 has already taken steps to avoid exposing NaN by way of treating text strings as the number zero; check out #1879, where it's discussed that this was an intentional spec change during the transition from 2.0 to 3.0. The fact that "(string) mod (number)" returns zero may just be another way of keeping in line with that decision.

That said, it's worth noting that "(number) mod (string)" -- swapping the order so the divisor is zero, rather than the dividend -- returns NaN, which is just as easy a way of exposing NaN. But this may not be a bug per se; it's being interpreted as "(number) mod (zero)", which returns NaN.

All in all the behavior at present can be boiled down to "strings are treated as the number zero in math operations", and thus the current behavior can be predicted...but only with an understanding of JavaScript's modulo operator behavior. (Or Scratch's, by way of experimentation.) So, the argument that "(text) mod (number)" returning zero is an arbitrary and confusing behavior as far as the user is concerned could still well stand; it's just worth keeping in mind that changing this behavior means shifting away from current Scratch spec.

(A tangential idea worth considering is that maybe "(number) mod (zero)" (and implicitly "(number) mod (string)") should return zero rather than the current NaN. Either direction the suggestion goes, it's still part of a debate over how important it is to hide NaN from users versus how much it makes sense to return NaN or zero in specific cases.)

**Comment by BryceLTaylor** [comment]
The current behavior is fine.  We'd prefer to return 0 than NaN.
