### ISSUE TITLE
Request for documentation - Broken link in docs/extensions.md

### ISSUE THREAD

**Issue by P3nny** [LLK/scratch-vm#3146]
We launched a scratch adaption for a german public broadcaster: https://programmieren.wdrmaus.de / https://github.com/wdr-data/code4maus
As a next step we would like to do a video tutorial series - and use the scratch-music extension for this, but we are having difficulties in integrating the music-extension in our scratch adaptation (codewise). 

Unfortunatly the link in this documentation file is broken: https://github.com/LLK/scratch-vm/blob/develop/docs/extensions.md
(https://github.com/LLK/docs/wiki/Extensions leads to 404) 

Honestly we are kind of stuck and do not understand how scratch-vm, scratch-blocks and scratch-gui play together in this case. 

Any hints are highly appreciated, all the best from Cologne,
thank you for all the great work,
Penny

**Comment by ericrosenbaum** [comment]
Hi- hopefully we can help! 

Sorry about the broken link. It actually points to a private repo and the page it links to does not actually contain the info you need.

The problems you're running into will depend on exactly how your own code is set up. You should not need to modify or build scratch-blocks. The extensions are inside of scratch-vm, and loaded by scratch-gui. The music extension should already be linked from the [extension manager](https://github.com/LLK/scratch-vm/blob/607cd2d392b0d16eb14e3512de9ac6741f2dfe3d/src/extension-support/extension-manager.js#L18). The GUI can then load it by id from the [extension library](https://github.com/LLK/scratch-gui/blob/3bec5545768a4c98e1075dc3726cc421037480d4/src/lib/libraries/extensions/index.jsx#L58).

If that doesn't help, can you describe:

- what exactly you're trying to do (e.g. add the extension to the scratch-gui extension library, or something else)?
- what you have attempted (i.e. a short description of the set of changes you made in order to try to add the extension)?
- what error messages you see when you load scratch GUI in the browser?

**Comment by ericrosenbaum** [comment]
Closing this - feel free to add comments if you want to document your solution to help others, or you can open a new issue if you have more questions.
