### ISSUE TITLE
Import watchers/monitors in SB2 importer

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-vm#343]
Moving from TODO comment. Currently these are ignored immediately.

**Comment by towerofnix** [comment]
Excuse me for posting this here, but I've already gotten through writing most of it and I don't have anywhere else to post it - I couldn't find an issue specifically dedicated to watchers anywhere! :)

If/when there *is* a better place to post this, I'd love it if this could be moved there (probably).

---

The basic VM code for this should be fairly easy, but some things to think about:

* Watchers obviously need a way to access their value - this could be done with [object getters](https://gist.github.com/liam4/3e189c229d0325dc5925d3598c7cfeba) or [values directly being set](https://gist.github.com/liam4/79e3175fed6a7de611d31c218edac0e2) (both could work, even at the same time, with getter syntax, which is a :+1: from me).
  * [List watchers can just use a reference to the array.](https://gist.github.com/liam4/e0cd143bad304089b5eff44aa3236bd1)
* Every watcher has "display settings"...
  * All watchers have X and Y positions, and can be hidden or shown. (Not necessarily directly through a Scratch project, but in the UI/on the stage you can toggle the display of all watchers [through context menu].)
  * List watchers have widths and heights.
    * New watcher designs might mean changes in how watchers will be positioned onscreen; overlapping watchers might be a problem in projects that have user interfaces based around watchers being positioned properly.
  * Slider watchers have a minimum and maximum value, which needs to be stored somehow.
* [Watchers can have the same label.](https://scratch.mit.edu/projects/132323269/) Because of this, watchers should probably be stored in an array, or with some kind of unique ID.
* [Watchers can be below sprites.](https://scratch.mit.edu/projects/132323841/) I do believe a fair amount of discussion on (whether or not to support) this might have already happened somewhere..
  * And above, by the way, if that wasn't implied.
  * In Scratch 2.0 I believe watchers are stored in the same list as sprites - an array called `children` under the stage object.
* Not all watchers can have every display type setting. For example, you can only change the size watcher to be a "normal watcher" or a "large readout", not a "slider". (I'm curious why?)

**Comment by mrjacobbloom** [comment]
Also, watchers reflect the color of data blocks, which can change in 2.0. I don't know all the details, but there are some quirks people have taken advantage of that you might want to consider: https://scratch.mit.edu/projects/977636/

**Comment by kchadha** [comment]
@paulkaplan adding you on this as well since it's on both of us this month.
