### ISSUE TITLE
Source map

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-vm#349]
Output file `vendor.js` can have source map to better browsing code and debugging.

**Comment by rschamp** [comment]
I don't think we've had too many issues with the current method, since we don't use obfuscated code in development.

Adjusting the source mapping can have dramatic effects on the build speed, so if we did change this we would need to do some tests to find which is the best balance between debug-ability and build performance.  If you would like to change the source map for your own development, you can do so by updating webpack's devtool config: https://webpack.github.io/docs/configuration.html#devtool.  In other words, you would stop using `npm start` or `npm run build` and run the webpack command manually, e.g., `./node_modules/.bin/webpack --progress --colors --bail --devtool source-map`.
