### ISSUE TITLE
Background flashing a lot in turbo mode (sample project)

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-vm#359]
### Expected behavior

_It does not flash._

### Actual behavior

_It flashes constantly kind of looking like it is losing saturation._

### Steps to reproduce

_Open the playground, turn turbo mode on, press green flag._

### Operating system and browser

_Windows 10 Google Chrome_

**Comment by tmickel** [comment]
I believe this could be the expected behavior for this project in turbo mode at 60FPS. The "compatibility mode + turbo mode" behavior is similar to Scratch 2.0 in turbo mode (https://scratch.mit.edu/projects/119615668/).

The code involved is "forever change color effect by 1".

In non-turbo mode, this means change the color effect once per frame. In turbo mode, this means increase by 1 as many times as possible within the interpreter's work time. The end effect is basically equivalent to "forever set color effect to random", because color effect is mod 200 and the number of times it can be increased in the work time is unpredictable.

I think the reason for the "desaturation/flashing" is just that this is how random color change appears to the eye. Maybe for example, two colors relatively opposite each other on the color spectrum presented in sequence will appear grey. Here is a project that takes advantage of that: https://scratch.mit.edu/projects/100403481/ (when you see one cat).

**Comment by thisandagain** [comment]
This is expected behavior for this project.
