### ISSUE TITLE
How is BlockType.BUTTON supposed to be used?

### ISSUE THREAD

**Issue by llunariis** [LLK/scratch-vm#3598]
I am writing a Scratch extension, and I want to know what the `BlockType.BUTTON` string does.

**Comment by towerofnix** [comment]
Check out [`test/unit/extension_conversion.js`](https://github.com/LLK/scratch-vm/blob/f405e59d01a8f9c0e3e986fb5276667a8a3c7d40/test/unit/extension_conversion.js) for an example, and [`src/extensions-upport/block-type.js`](https://github.com/LLK/scratch-vm/blob/f405e59d01a8f9c0e3e986fb5276667a8a3c7d40/src/extension-support/block-type.js#L11-L14) for its official description: "A button (not an actual block) for some special action, like making a variable."

Finally, you can see how scratch-vm exposes buttons to scratch-blocks (the actual block programming interface based off of Blockly) in [`src/engine/runtime.js`](https://github.com/LLK/scratch-vm/blob/80e25f7b2a47ec2f3d8bb05fb62c7ceb8a1c99f0/src/engine/runtime.js#L1229-L1250).

The important thing is that they aren't *especially* useful yet, because extension support hasn't been fully completed:

```js
// for now we only support these pre-defined callbacks handled in scratch-blocks
const supportedCallbackKeys = ['MAKE_A_LIST', 'MAKE_A_PROCEDURE', 'MAKE_A_VARIABLE'];
if (supportedCallbackKeys.indexOf(buttonInfo.func) < 0) {
    log.error(`Custom button callbacks not supported yet: ${buttonInfo.func}`);
}
```

If you want to expose the "make a list", "make a custom block", or "make a variable" buttons from inside your extension, though... this is the way to do it :P

Hypothetically, this would support "custom callbacks", probably for creating custom variable types, connecting devices, or opening other dialogs / performing other actions. But since support hasn't been added for that (or specified/designed to my knowledge), you'll either have to code it yourself in a fork of scratch-vm, or make do without it :package:
