### ISSUE TITLE
How to create a custom block that saves the screenshot to the costume. Especially when using a webcam. how can we capture images in scratch?

### ISSUE THREAD

**Issue by edwinjosechittilappilly** [LLK/scratch-vm#3691]
We are trying to capture images using the video sensig module and to use it as the current costume.
Any suggestion on how to achieve that?

**Comment by ericrosenbaum** [comment]
Interesting question! We are not likely to exploring saving images automatically, especially from the webcam, because there would be trouble with both privacy and file size. 

If you just want to try it out, there something similar available in Snap!, blog post about it here: https://forum.snap.berkeley.edu/t/paste-a-sprite-on-another-sprite/709
