### ISSUE TITLE
Update Dropdowns When New Sprite Created

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-vm#416]
### Expected Behavior

Point toward __, go to __, touching __, and distance to __ should include references to newly created sprites.

### Actual Behavior

They don't.

### Steps to Reproduce

Create sprite, use block.

### Operating System and Browser

Ubuntu 16.04, chrome 56.0.2924.76 

I am sure you're already working on this, just adding an issue so I can share our first play test findings / complaints.

**Comment by TheBrokenRail** [comment]
I have a implementation of this that uses Blockly.Blocks.Sprites to hold sprite data, this issue is expanded on in LLK/scratch-blocks#749 my closed pull requests for this are #382 and LLK/scratch-blocks#770

**Comment by TheBrokenRail** [comment]
This was fixed by LLK/scratch-gui#343

**Comment by towerofnix** [comment]
~~Note that *this* issue was fixed by that PR, but costume and sound blocks still have the same issue (that is, when the sprite's costume/sound list is modified, those changes aren't reflected in the block dropdown).~~

edit: I wonder why..? That PR looks to be a general fix, you'd think it would apply to costume and sound blocks..

edit 2: Of note, clicking "duplicate" on the block fixes it. Is there maybe a menu-item cache...?

edit 3: So either there's a cache or the block objects are being re-constructed every time the block workspace changes (i.e. because a different sprite is selected). Whichever way it means that the menus still aren't updating whenever they're clicked on.

edit 4: I was all wrong apparently? Running from a local build worked!
