### ISSUE TITLE
Should the webpack build still be building extension-worker.js ?

### ISSUE THREAD

**Issue by dalelane** [LLK/scratch-vm#4356]
Building scratch-vm used to produce `extension-worker.js` in dist/web

But since the recent webpack changes, it no longer does. I'm not sure when that changed... perhaps somewhere around https://github.com/scratchfoundation/scratch-vm/commit/058685f41ea950e789aa5c9cad133a86fa8bf963 ?

There are still consuming projects that depend on extension-worker.js being built 
e.g. 
https://github.com/scratchfoundation/scratch-gui/blob/13aa69ebe6c5e3e960f985bb5abcb65c1610bcc4/webpack.config.js#L210-L211 

Is this just because they haven't yet been updated, or is it an oversight and the scratch-vm webpack config needs another change?

My assumption is that it's the latter because I think `loadExtensionURL` still assumes there will be an extension-worker.js script 
https://github.com/scratchfoundation/scratch-vm/blob/9af4a742098bdd90608130e3d84966379235ed61/src/extension-support/extension-manager.js#L160

**Comment by DharaniMahesh** [comment]
Because of this the customs extension which we create on our own are not working too. After creating the extension and assigning the path to the id of newly created extension in extension-manager.js, When I click on the extension in the frontend I'm getting the following error 'GET http://localhost:8602/extension-worker.js 404 (Not Found)'. I removed changes done in extension-worker.js done in that commit but I'm still getting the same error.

**Comment by dalelane** [comment]
I believe this has been fixed by https://github.com/scratchfoundation/scratch-vm/commit/4f146d6290dad94b37d3ee32a9f86aea551e396e
