### ISSUE TITLE
Switching to undefined costume switches to last costume

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#489]
From a Scratcher:
> Switching to a non-existent costume name now switches to the last costume, previously it didn't switch at all. This breaks some case sensing and possibly other projects.

**Comment by SillyInventor** [comment]
I think this is because Cast.toNumber is different from Interpreter.asNumber. Specifically, toNumber will return 0, instead of NaN, so you will never get an input that won't return a costume.

**Comment by Mr-Dave2** [comment]
I noticed that this issue is closed but the problem still partially exists and that it currently has a "help wanted" tag.

This costume switching glitch is a problem for this project https://scratch.mit.edu/projects/115578835/ by @Amylaser.  (This might change because the author knows about the problem and says she has a workaround, _Edit:  I'm not sure how common this technique is.  I think I just got lucky at first with finding a couple that have this problem when looking for problems with text engines._).

Scratch 3.0 will switch to the last costume in the set of costumes if the program attempts to switch to a costume that is named with just one or more spaces and that name does not exist.  The expected behavior (under Scratch 2.0) is that the costume would not switch.

I've written a small test case:  Links are: [2.0](https://scratch.mit.edu/projects/236483492/) and [3.0](https://preview.scratch.mit.edu/#236483492)

[<img src=https://cdn2.scratch.mit.edu/get_image/project/236483492_144x108.png>](https://preview.scratch.mit.edu/#236483492)

Another example of a user project with this issue is [here:](https://preview.scratch.mit.edu/#98678495)

Of course it's easy for a user to correct this (as I said, the author of the first example already knows what to change).
