### ISSUE TITLE
Should the <key [x] pressed?> boolean reporter accept an input?

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#500]
The < key [space] pressed > boolean reporter does not accept an input in 2.0, but currently in 3.0 it does.

I got excited for a minute about this because it could become a feature: you could for example loop through a list of letters, to check if each is pressed, rather than using separate if statements. This already works in 3.0 for letters, but numbers seem to be treated as ascii codes, so they do not work as expected (but, due to this, checking < key 10 pressed > is true when you press tab!). 

I think this feature would require some changes to the way the [scratchKeyToKeyCode](https://github.com/LLK/scratch-vm/blob/develop/src/io/keyboard.js#L23) function works.

**Comment by mrjacobbloom** [comment]
note that some Scratch 2.0 projects use a hacked <key [] pressed> blocked already, which might break if the functionality changes. I believe Griffpatch wrote a key->ascii project that detects keys not in the list

**Comment by ed-cooper** [comment]
Overall, I think this would be beneficial

**Reasons for:**
- A lot of people hacked this block in Scratch 2.0 for convenience (allowing them to loop through keys) or to access keys that were not otherwise exposed (eg. backspace)
- It is confusing to less experienced Scratchers how people got reporters in the block (as they don't understand 'hacked blocks')
- Scratch 2.0 (indirectly) supports this and a lot of projects with hacked blocks rely on it, so at least the backend code should work with it for compatibility (even if you decide to not allow reporters to be dropped in it)
- Pretty sure I've seen this as a requested feature on the forums before

**Reasons against:**
- Some of the hacked codes aren't entirely obvious - eg. the backspace character is rendered simply as a space (so people would struggle getting it to work)
- Some keys have multiple names - eg. 'up' vs 'up arrow', 'back' vs 'backspace' - doing this might mean that you'd have to check for both in the interpreter (though they should be inferred from the drop down options on the block)
- Localisation - if a project has a variable set to 'up arrow' and uses that for the input, but the user has the editor in Arabic (example), it should still recognise it as the up arrow (I don't know how translations affect this block currently as I've never used the editor in a none-English language)
- Other drop down inputs don't allow reporters, and the difference in shape might not be obvious if you weren't aware of the meaning of the shapes
- Potential confusion for new scratchers (?) - eg. placed variable labelled 'a' with value 0 inside the input, then expects a key to be detected (unlikely case imo)
- What to do if a given key doesn't exits? (eg. hello) I presume returning false is the simplest answer, but if Scratch 3 were to support error messages at any point there might be an opportunity to display an error there

I think I've covered most arguments

**Comment by towerofnix** [comment]
>Potential confusion for new scratchers (?) - eg. placed variable labelled 'a' with value 0 inside the input, then expects a key to be detected (unlikely case imo)

I agree that this probably isn't a very likely case. More likely than dropping a variable named '10' into the "move steps" block, but not by much.
