### ISSUE TITLE
Clock face draws incorrectly

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#520]
### Expected Behavior

This 100% pen [project](https://scratch.mit.edu/projects/141331752) draws a working clock, and in Scratch 2.0 it looks like this:

<img width="479" alt="screen shot 2017-04-04 at 6 00 12 pm" src="https://cloud.githubusercontent.com/assets/567844/24680883/9f1d3f24-1960-11e7-8a7c-01315a7f3897.png">

### Actual Behavior

In Scratch 3.0 it currently looks like [this](https://llk.github.io/scratch-gui/#141331752/):

<img width="478" alt="screen shot 2017-04-04 at 5 59 54 pm" src="https://cloud.githubusercontent.com/assets/567844/24680892/a4e51d6e-1960-11e7-9c85-2bfdf690d2b7.png">

There several issues here, so It's a bit hard to diagnose. There could be a trigonometry quirk involved (@paulkaplan), or some detail of the way the pen works (@cwillisf).

### Steps to Reproduce

Visit:
https://scratch.mit.edu/projects/141331752
https://llk.github.io/scratch-gui/#141331752/

### Operating System and Browser

Mac OS 10.11.6 Chrome 57

**Comment by paulkaplan** [comment]
I've simplified this down to the following project:
![screen shot 2017-04-06 at 12 06 36 pm](https://cloud.githubusercontent.com/assets/654102/24764184/87bafc24-1ac1-11e7-834d-81c995f807f0.png)

**Comment by paulkaplan** [comment]
Seems to have to do with the fact that there is a 0x0 px costume. When I duplicate the sprite and add a 3x3 px dot costume, it works in 3.0:
![screen shot 2017-04-06 at 12 12 56 pm](https://cloud.githubusercontent.com/assets/654102/24764458/65b7bcce-1ac2-11e7-8772-5fc543903366.png)

I believe this is being caused by incorrect "fencing", I think coming from the renderer function `getFencedPositionOfDrawable` when there is a 0x0 sprite. @cwillisf do you think this error is correctly filed in VM, or should it be in render?

**Comment by ericrosenbaum** [comment]
Looks related to https://github.com/LLK/scratch-render/issues/53

**Comment by CatsAreFluffy** [comment]
Seems like the sprite is constrained to the +x-y quadrant (except for the digital time, for some reason, seems to be clamped to +y)

**Comment by CatsAreFluffy** [comment]
The 3.0 version of the project fails to load for me (no scripts exist)

**Comment by ericrosenbaum** [comment]
fixed by https://github.com/LLK/scratch-render/pull/156
