### ISSUE TITLE
Cannot load projects

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#543]
### Expected Behavior

Should be able to load existing Scratch projects via the `/#{project_id}` path convention.

### Actual Behavior

Either:
- Project does not load (hangs)
- Project loads and then is immediately replaced by the default project
- Project loads but blocks are not visible

### Steps to Reproduce

Load any of the following (you may need to refresh and make multiple attempts):
https://llk.github.io/scratch-gui/#156451053
https://llk.github.io/scratch-vm/#142330668
https://llk.github.io/scratch-vm/#141331752

### Operating System and Browser

Mac OS 10.12.4  |  Chrome Version 57.0.2987.133 (64-bit)
Mac OS 10.12.4  |  Firefox ESR 45.7.0

**Comment by cwillisf** [comment]
@lifeinchords brought to my attention another, hopefully related problem today: the sprite info report event goes crazy, causing extreme CPU load when switching your edit target sprite. On Firefox in particular, this winds up causing `TypeError: attempting to access detached ArrayBuffer` deep inside `lodash.defaultsdeep`.

This project is a good repro case:
https://llk.github.io/scratch-gui/#144852507

Feel free to split this off if it turns out to be unrelated.

**Comment by rschamp** [comment]
@cwillisf Would you log that separately?

The issues of loaded projects being replaced by the default project and blocks not being visible issue has been fixed by https://github.com/LLK/scratch-gui/pull/325 and #542 respectively.  I think the hanging issue has was also fixed by https://github.com/LLK/scratch-gui/pull/325, although a couple of the example projects are large and have non-standard project json causing many warnings in the console, so appear to hang but eventually do load.

**Comment by cwillisf** [comment]
High CPU load while switching sprites has been filed as LLK/scratch-gui#329
