### ISSUE TITLE
Discussion - Many larger projects do not load / unusable

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#550]
Filing an issue to track this as it's something we should discuss. Many mid-sized projects (such as the one below) currently cannot be loaded into the GUI. I haven't spent too much time in the profiler yet, but a cursory glance shows that we are burning through memory and CPU even when the editor is idle.

#### Mid-level Complexity Project
- `https://llk.github.io/scratch-gui/#155128646`
- Press green flag
- Profile / observe performance

#### Simple Project
- `https://llk.github.io/scratch-gui/#158487479`
- Press green flag
- Add a new sprite
- Profile / observe performance

**Comment by rschamp** [comment]
The serialization fix only addressed the issue with adding a new sprite in the simple project. There is still work to be done for the mid-level complexity project performance. Though I wonder if we need a general purpose issue like this for it, or should we investigate and file more specific performance issues?

**Comment by cwillisf** [comment]
IMO the performance problems we were having before were bad enough to count as "broken" rather than just "not done yet" so this issue was justified at the time. If we've improved to just "not done yet" levels of performance problems (have we?) then I would be OK with closing this. If not, I'd prefer to leave this open until we identify the main things that are pushing into "broken" territory.
