### ISSUE TITLE
Add blocks to set drag mode for sprites

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#553]
Due to the removal of the "draggable" toggle in the sprite info pane, users will still need a way to toggle the draggable behavior of a sprite. Should we match the behavior found in the "set rotation style" block and add a new block to the "Motion" category? Or do we need to add a second level of "depth" to the sprite info pane (similar to what we have today in 2.0)?

/cc @carljbowman @ntlrsk

**Comment by mrjacobbloom** [comment]
I'd vote for both options:

- It's important to have draggable status indicated (if not toggleable) in the info pane because there's literally no way to distinguish between a draggable- and non-draggable sprite in the editor, and any differences between the editor and the player should be clearly marked so that users know what they're sharing
- I'd also support a new block because it'd be nice for more advanced users to be able to be able to toggle draggability while a program runs. Right now, people have to use hacks to temporarily disable dragging, like putting a clear sprite over the target sprite to intercept drags

**Comment by Grinthy** [comment]
Yeah, I agree with the above.

**Comment by thisandagain** [comment]
@carljbowman This is a detail that we dropped. We should sort out a fix next month.

**Comment by thisandagain** [comment]
@paulkaplan @carljbowman @ericrosenbaum Resolving this is a blocker for the preview release.

**Comment by thisandagain** [comment]
From conversation today:
- Add block to the "Sensing" category after the `mouse y` reporter
- `set drag mode [draggable / not draggable]`

**Comment by paulkaplan** [comment]
@thisandagain I implemented the three parts of this (vm, blocks and toolbox in the GUI) but as a note, I didn't realize that the drag mode only impacted the player. Two things from that:
1. Will other people be confused by that? Using the block in the editor has no effect.
2. We don't have a player right now, so the block doesn't actually do anything. is that ok for now? should impact "fullscreen mode" as if that was the player?

**Comment by jojomoore2007** [comment]
> @thisandagain I implemented the three parts of this (VM, blocks, and toolbox in the GUI) but as a note, I didn't realize that the drag mode only impacted the player. Two things from that:
> 
> 1. Will other people be confused by that? Using the block in the editor has no effect.
> 2. We don't have a player right now, so the block doesn't actually do anything. is that ok for now? should impact "fullscreen mode" as if that was the player?

Fullscreen mode is impacted by this. Thanks!
