### ISSUE TITLE
"Pick random" value as input to "wait" is ignored 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#591]
### Expected Behavior

The "pick random" block should output a number that the "wait" block can use as a number of seconds. 

### Actual Behavior

The value from the "pick random" block seems to be ignored, and the "wait" block always waits one second.

### Steps to Reproduce

Create and run this stack:

<img width="286" alt="screen shot 2017-06-05 at 2 34 19 pm" src="https://cloud.githubusercontent.com/assets/567844/26797914/9f46824a-49fc-11e7-9a5f-f46c3d689117.png">

It should play the "pop" sound at a random interval of 1 to 5 seconds, but it plays every second.

### Operating System and Browser

Mac OS 10.11.6 Chrome 58.0

**Comment by thisandagain** [comment]
This also feels like a blocker for the upcoming play test.

**Comment by ericrosenbaum** [comment]
I have a clue about this. Logging the value of the input (args.DURATION) in the wait block implementation [here](https://github.com/LLK/scratch-vm/blob/ecf535f4c3d4f5820ea969bb23a24ff4f6f4770b/src/blocks/scratch3_control.js#L76-L88), shows it running dozens of times, once per frame, with a different random value each time. 

So, it seems to be re-evaluating the inputs every frame as it waits. So I suppose the input needs to be evaluated just the first time, and stored.

The wait block uses util.stackFrame.timer, but for other blocks that wait we've used a Promise resolved by a setTimeout, which is simpler and wouldn't have this problem. But maybe there's something different about the way the stackFrame timer works which we need here?

**Comment by ericrosenbaum** [comment]
The "rest" block (in the sounds category) is implemented using a Promise and setTimeout, which you can see [here](https://github.com/LLK/scratch-audio/blob/19e1136e3b3a44a041f0f89eea2d2a19ec238175/src/index.js#L289-L301). This is equivalent to the example shown above, but behaves correctly:

<img width="296" alt="screen shot 2017-06-05 at 3 09 02 pm" src="https://cloud.githubusercontent.com/assets/567844/26799117/3d6dd248-4a02-11e7-8914-2a21a3e6eb12.png">

**Comment by ericrosenbaum** [comment]
@tmickel @thisandagain @rschamp before we close this I want to confirm that this doesn't cause some other problem! specifically, is there a difference between using the stackframe timer like [this ](https://github.com/LLK/scratch-vm/blob/ecf535f4c3d4f5820ea969bb23a24ff4f6f4770b/src/blocks/scratch3_control.js#L76-L88 )and using a promise like [this](https://github.com/LLK/scratch-audio/blob/19e1136e3b3a44a041f0f89eea2d2a19ec238175/src/index.js#L289-L301) to make the wait block wait.

**Comment by fsih** [comment]
https://github.com/LLK/scratch-vm/commit/e49f076fa1cf2f15839755f1edea471c5f19f249

Looks like this commit did the opposite, going from a promise to a  stack frame. It's unclear why though

**Comment by tmickel** [comment]
Ahah...what a problem. Sorry about this.

Some more exposition regarding the "wait" blocks: I think this is a pretty interesting problem actually. On the one hand we have "wait until <>"-type blocks which _demand_ that the input is re-evaluated every frame; on the other hand we have "wait () secs" which should only evaluate the input once. Actually the best solution is probably to inform the interpreter about this situation in a clear way.

I believe a related problem is "repeat () times". This likely _has the same bug_ (!), except, to track how many times repetition has occurred, the iteration account is saved when the block is first run (and subsequent re-evaluations of the input are thrown away). So, I believe, it's probably true and quite bad that "repeat () times" actually evaluates the input every iteration (even when the value is ignored) - i.e., in https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_control.js#L44 `times` is thrown away, so the problem never manifests to the coder.

To fix `wait`, you have three options: switch to the Promise, save `duration` (https://github.com/LLK/scratch-vm/blob/develop/src/blocks/scratch3_control.js#L83) on the first run (like you mentioned above), or solve the underlying problem (get the interpreter to not re-evaluate the input in this situation and probably a few other blocks).

To answer your question:::::

The Promises stuff seems stable and a solid short-term solution (at least) to me. One thing to have caution about is that a `setTimeout` can only resolve at certain points in the browser lifecycle - notably, when no other JavaScript is running. I believe this means a Promises-based solution will sometimes have `wait` blocks that wait for at least an extra frame as compared to checking a numerical timer inline (i.e. if the timer would have resolved while the interpreter loop was running, but instead needs to wait until the browser is idle). should be a difference of tens of milliseconds, but maybe it matters with waits, or maybe it doesn't - not sure :)

**Comment by towerofnix** [comment]
I'm new to how the interpreter for Scratch 3.0 works, so I might be getting any of this wrong :)

Do inputs for blocks that pause the interpreter get evaluated *every time* the interpreter ticks that block? If so, *why?* What block ever needs to get a new value, past the first tick it's run?

It looks like you already save data on the stack frame, e.g. in the `glide` definition:

```js
if (!util.stackFrame.timer) {
    // First time: save data for future use.
    util.stackFrame.timer = new Timer();
    util.stackFrame.timer.start();
    util.stackFrame.duration = Cast.toNumber(args.SECS);
    ...
```

So.. in the `glide` definition, the block for `args.SECS` being evaluated *every time* the glide block is ticked?

This could have potentially disastrous effects, in the context of reporters that have side-effects — these could be user-defined custom reporter blocks (if such existed) or user-defined extension blocks (as in 2.0).

(Obvious example: imagine calling a user-defined "list pop" block inside of a "wait (n) secs" block, and having all of the items in the list pop off, one for every Scratch tick the "wait" block is running..)

I've personally got a couple of ideas on how I'd implement the interpreter input evaluation differently myself, but, you know, that's rewriting parts of an interpreter, which I'm not sure is actually an open "help/input wanted" project 😛

**Comment by tmickel** [comment]
@liam4 All of that is more or less right. The inputs probably _shouldn't_ be evaluated every tick by default.

But, there is at least one case where the input _must_ be evaluated every tick: "wait until <boolean>". "repeat until <boolean>" is similar, although complicated by the fact that it steps into/out of the branch.

The tricky bit will be covering both cases in a clear way.

P.s. in the Scratch 2.0 interpreter, handling this was simplified because block implementations do "their own deciding" about when their inputs are evaluated. It's possible that the nicest solution could be to refactor the 3.0 interpreter to work similarly, it's a different abstraction (in 3.0 thus far, to the block implementation inputs are "ready-to-go" and evaluated at the start).

**Comment by towerofnix** [comment]
The 2.0 interpreter is pretty similar to the way I'd do it, yeah. Evaluate arguments on demand. I think that would theoretically make things the least complicated and most explicitly clear; though it would, of course, take a bunch of refactoring!

**Comment by tmickel** [comment]
could be worth trying :) also might have performance benefits. the original reason for this way was having a good API for Scratch extensions (which maybe shouldn't have to evaluate their own inputs) and have the default blocks use the same API. But maybe something could satisfy everything...

**Comment by mrjacobbloom** [comment]
I don't know too much about Snap! but I know that they make the distinction between code that's passed as a value (evaluated once) or as raw code (to be handled some other way), I believe that's what the rings are for. Someone back me up here since I don't know what I'm talking about

**Comment by towerofnix** [comment]
@mrjacobbloom funnily enough that's was the topic of what I originally had written as a response to this thread, but it became really long and inconvenient..

Basically Snap<i>!</I> distinguishes between *normal* inputs and *unevaluated* inputs. They both look the same to the user, but unevaluated inputs actually give the implementation the *block* in the input, rather than the *value* of the block in the input.

(@mrjacobbloom was talking about the "ring" inputs, which are practically the same as unevaluated inputs, but they look different. Ring inputs make it explicitly clear you want a *block*, and not a string or number value, as the input.)

The thing is, that distinction is made inside of the block's definition — i.e., the same place its spec and what-not are stored. So, to store input (un-)evaluation options, you'd have to put them inside of scratch-blocks, and obviously that specific block information is better fit for scratch-vm. That's why going with simply evaluating on demand (i.e. *all* inputs are unevaluated) might be an easier, but just as effective, option.
