### ISSUE TITLE
Suggestion: Real local variables

### ISSUE THREAD

**Issue by greenSnot** [LLK/scratch-vm#597]
There are few kinds of local variable:
1) sprite-scope, Like scratch2.0
2) block(group)-scope, or rootblock-scope, like closure-scope
```
(function () {
  var a = 1;
})()
```
3) statement-scope, strict local variable, like
```
if {
   let a = 1;
} else {
   let a = 2;
}
```

I think (2) is better, that makes local variable in each recursion available and more convenient than strict local variable.
```
function search(depth, s) {
  if (depth > 3) {
     //do something
     return;
  }
  for (var i = 0; i < 10; ++i) {
    search(depth + 1, i);
  }
}
```

**Comment by towerofnix** [comment]
Ah, to clarify:

![demo](http://i.imgur.com/i4cQ941.png)

Local variables take a lot of work to get right... and, of course, in languages like JavaScript, they've caused [plenty of confusion](https://stackoverflow.com/questions/111102/how-do-javascript-closures-work), so:

* You want good documentation for how (script-) local variables work. This documentation should be understandable to kids who are new to programming.

* Maybe more importantly, you need it to be self-descriptive. Most people won't look at the documentation! And this is difficult, since two people might give totally different answers to my question in the script picture:

  * "You need to put the `create variable` block at the top – since you can't get that variable outside of the if-else branch it's in."

  * "Well, it doesn't matter which way you do it – either way you're creating the variable before running the `say` block."

There's a bunch of good discussion about script-local variables on the Scratch forums, but the site isn't working right now, so I can't get you any links :)

**Comment by greenSnot** [comment]
@liam4  You don't need to create a variable at the top because all the variables had declared in toolbox.They can choose local/global at that time.

**Comment by rdococ** [comment]
I'm just some dude from the internet (well, I do use Scratch regularly) giving my 2 cents.

I agree that if script-local variables are going to be added, they should be added right. That is to say, they should be intuitive and easy to grasp for newer Scratchers.

**Appearance:** I think that the block to create a script-only variable should be called "create a script-only variable named (my variable)". This would be an attempt to ensure that a new Scratcher can easily determine what the block should, roughly, do, before they've started experimenting with it, and it also clarifies the scoping rule - the script-only variable is for this *script*, not this particular C-mouth.

**Scoping rules:** I think that a script-only variable should be available for the entire script from the point it was created onward. This means that in the examples given by @towerofnix, either script would work. I would also consider custom block definitions to be "scripts" of their own, as opposed to sharing their variables with the script that runs them - this means that a custom block can use script-only variables without worrying about collisions, and it would better support recursion for custom blocks that use script-only variables, and it also works visually - the variables in this custom block definition are a part of this custom block definition and nothing else, while the variables in that script that uses this custom block are a part of that script only.

**Mockups:** Here are ideas of what I think it could look like. The colors for the blocks aren't final, but because there are already many pink, red, orange and yellow blocks (sounds, custom blocks, lists, variables, events and control), I decided to go for a darker shade of pink. The reason I wanted to stick to a shade of pink for these mockups is to create a connection between these script-only variables, and custom block parameters which are also script-only.
(I'm using s3Blocks here, which is in its beta, so it might look a bit off in places.)

![count up to n with local var](https://user-images.githubusercontent.com/3169568/48382014-dd994780-e6d6-11e8-8b0a-7d308894c12f.png)

The above example demonstrates what a simple "count up to N" block might look like.

![fibonacci example with local var](https://user-images.githubusercontent.com/3169568/48382437-0de1e580-e6d9-11e8-8188-ffff4dd6715d.png)

This use case is one of my favorites. We can calculate a value from a custom block, and use it multiple times over the course of a script because we don't have to worry about other scripts that need to calculate stuff, at least if the block itself is "run without screen refresh", bringing us ever closer to custom reporters even if we don't actually get 'true' custom reporters.

**Comment by mrjacobbloom** [comment]
Hm... I think a lot of these cases would also be covered by blocks that let you set/change procedure arguments. In that case, the scoping would be obvious and the `create script variable` block would be unnecessary. The problem is that it would lead to extra args on procedures, which would definitely get confusing.

Also, in either this situation or the script-scoped variables, I don't know what the var dropdown would contain... would it be empty/disabled when not attached to a stack, or would it contain all of the arguments/script-vars that exist anywhere? Would it just be a string input, which people would definitely try to drop the variable itself into? None of those sounds great to me.

**Comment by greenSnot** [comment]
Could we do it just simply by:
```
set variable[x] to [1] // global x
...
if statement
declare local variable[x]
set variable[x] to [1] // local x
```
Here's an example, variable block uses string input(static, can't be modified on runtime) instead of dropdown. It might be better.
https://greensnot.github.io/ZeusPlayground/dist/

**Comment by rdococ** [comment]
> which people would definitely try to drop the variable itself into?

The 'set' and 'change' blocks could have an unevaluated variable reporter input, which Scratchers could drag variables and parameters into.

**Comment by rdococ** [comment]
To be honest, this is only really useful in advanced projects. You only need these if you're doing particularly complex recursive calculations and/or want to run custom blocks from multiple scripts at once. Anything else and sprite vars & lists will do, and you can inspect the values for easier debugging.

In the language of Scratch's design goals, I think it raises the floor to make the ceiling easier to reach 🙂

Where it's useful, it's _really_ useful, but maybe still not worth the extra cognitive load on new Scratchers.
