### ISSUE TITLE
Error when preparing the environment running npm install

### ISSUE THREAD

**Issue by Andrewyg** [LLK/scratch-vm#600]
### Expected Behavior

According to the README after I run `npm install https://github.com/LLK/scratch-vm.git` I should have an environment for developing
### Actual Behavior

I run the npm install command but it cames out error and in my experience after npm install should be a Project name not URL

### Steps to Reproduce

open powershell or cmd run the command provide by README.md `npm install https://github.com/LLK/scratch-vm.git` then you'll see the error

### Operating System and Browser

Window 10

###pictures
<img width="960" alt="2017-06-11" src="https://user-images.githubusercontent.com/20808546/27008303-b2cc984c-4ea0-11e7-9a98-dc133840549a.png">

<img width="960" alt="2017-06-11 1" src="https://user-images.githubusercontent.com/20808546/27008304-b2cd627c-4ea0-11e7-9391-54db0f6eaae5.png">

**Comment by rschamp** [comment]
Thanks for your report @Andrewyg. It looks like you don't have Git installed, which is required to install from GitHub.

Also, the README is out of date. Installing via git will no longer work as expected, since we are not storing the build in git, and instead publishing it to NPM.

The method you were attempting will not set up a development environment for scratch-vm, but is what you would want if you want to use scratch-vm in your own application.

I will update the README to be clearer and accurate.
