### ISSUE TITLE
Implement argument reporters in the VM

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-vm#699]
See https://github.com/LLK/scratch-blocks/issues/1102 and https://github.com/LLK/scratch-blocks/issues/1110

On the VM side:
- [x] Track duplication of argument reporters as they are dragged out of the define block
- [x] If used in a custom block with that argument name, they act like local variables
- [ ] If used in a custom block without the argument name, evaluate to zero/the empty string/false
- [ ] If used outside of custom blocks, evaluate to zero/the empty string/false
- [x] They may have the same names as global variables

**Comment by thisandagain** [comment]
@paulkaplan Adding you to this as per the current schedule for Custom Procedures.

**Comment by paulkaplan** [comment]
Interesting, the scratch 2 behavior of args outside of the define stack is... not what I expected. All types evaluate to 0 (not empty string/false for string/booleans)

![arg-outside-stack-scratch-2](https://user-images.githubusercontent.com/654102/33671983-0df308de-da77-11e7-84a5-9b37e0f63094.gif)

@thisandagain I'm worried about changing the behavior of that in case any old projects rely on it? It isn't super important that they evaluate correctly, since args outside of a define stack put you pretty far out in "undefined behavior land". But still seems strange. Should I just follow scratch2 behavior if/until it is reported as a problem? Or change it so booleans report "false" and strings report ''?
