### ISSUE TITLE
Touching color white always returns "true"

### ISSUE THREAD

**Issue by ChampikaF** [LLK/scratch-vm#710]
### Expected Behavior

Should only return true when touching white, otherwise false

### Actual Behavior

Always returns true

### Steps to Reproduce

https://llk.github.io/scratch-gui/#179622724 
Click on the "touching color" block - it will return true

### Operating System and Browser

Mac OS Chrome 61

**Comment by Tymewalk** [comment]
Just confirmed on Ubuntu Linux 16.04 LTS, Firefox 55.0.

For some reason, moving the Saturation slider out and then back to the left side gives it a saturation value of 2, and it still reports true when it's set that way. I don't know if that's intended based on how `touching color []?` is supposed to work, or why it can't go lower than 2.

**Comment by Tymewalk** [comment]
I wasn't using the development version, so the buggy slider is already fixed. It still returns true on the development version for saturation <2 or brightness >96 though, which I'll assume is intended.

**Comment by griffpatch** [comment]
This issue is occurring because of how we detect the color under a sprite.
* First we set up a detection canvas (g1)
* Fill it white (background color)
* Then we paint the sprites & background under the sprite masking them to the shape of the original sprite we are detecting against.
* Finally we look to see if there are any pixels in the resulting image that closely match the color we were looking for.

So the issue is simple... We start by filling the detector canvas with the color white! Then obviously there will be white in the final image (due to the nothing being painted over the clipped areas)

Here is the line that fills the detecting canvas white:

https://github.com/LLK/scratch-render/blob/998d3e129a71eefea7aaee57fb9b76b9f36b9e71/src/RenderWebGL.js#L442-L443

Here is a screenshot of the color test for white along with it's debug-canvas showing LOTS OF WHITE :)

![image](https://user-images.githubusercontent.com/6737342/32606198-4e8a02c0-c54c-11e7-8429-dc5c69693680.png)

If we fill the detection canvas black instead, then the color test for white succeeds :)

![image](https://user-images.githubusercontent.com/6737342/32606247-7d86d94a-c54c-11e7-9eae-a3a52ed01b9c.png)

I did this by adding a test for the color we are looking for (white in this case) and changing to fill the background black in those cases... However, I feel there may be a more scientific approach...?
