### ISSUE TITLE
The '(variable name) of (sprite name)' reporter block is broken

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-vm#711]
### Expected Behavior

The '(variable name) of (sprite name)' reporter blocks would return the variables value.

![image](https://user-images.githubusercontent.com/6737342/31545290-92e0d8a4-b016-11e7-9306-022412cb5486.png)

![image](https://user-images.githubusercontent.com/6737342/31545298-9f8ff67a-b016-11e7-96ce-7ea98a6ef39b.png)

### Actual Behavior

This used to work, but must have broken at some point because it now always return 0.

### Steps to Reproduce

Load this project: https://llk.github.io/scratch-gui/develop/#26861174
* On "Sprite1" click on the join block to reveal the value of the local variable 'aaa'. It should be 'aaa = AAA'
* Now, on "Sprite2" click the join block to reveal the same value referenced using the 'of' block. The answer should be 'AAA', but instead it is '0'.

### Operating System and Browser

Chrome browser on windows 10 PC

**Comment by towerofnix** [comment]
>This used to work, but must have broken at some point because it now always return 0.

Hm, that's interesting. I recall implementing the OF block myself (https://github.com/LLK/scratch-vm/pull/311); I'll take a look (but I don't guarantee I'll find a solution :) ).

**Comment by towerofnix** [comment]
It looks like variables are now prefixed by an ID in the variables array..

![Screenshot of sprite.variables object](https://user-images.githubusercontent.com/9948030/31550234-0b0199be-b007-11e7-90c1-51304043a071.png)

I'll have to look at the commit that made that change. I'm guessing there's a dedicated function on sprites to get the value of a local variable.

**Comment by towerofnix** [comment]
Discussion on behaviour is needed.

Every variable in a project has a unique ID - this doesn't change, even if the variable is renamed. I believe this is used to make renaming variables easy (though correct me if I'm wrong).

At the moment, a simple change is to make the "(property) of (sprite)" block search the variables object for a variable whose name is the same as `args.PROPERTY`.

The other option is to make the "(property) of (sprite)" block take a variable input the same way `getVariable` does - that is, it would be given a variable ID instead of a variable name. (This would require some work in scratch-blocks to make the dropdown behave properly, I think; the menu would be a mix of normal attributes (x position, costume name, etc) and variable IDs/names.)

However, this would be a *breaking* change. Many projects\* use the hacked block "((variable) of sprite)", where "(variable)" is actually a reporter. The value in "(variable)" is simply a variable name, such as "A" or "B", not a variable ID, such as "ABCD321-efg,Xz-A". If OF expects a variable ID (and not a name), this would fail. Furthermore, this *isn't* a hacked block in 3.0 -- the OF block now accepts reporters in both its menus, not just the sprite name.

---

\* For example, griffpatch's [pen text engine](https://scratch.mit.edu/projects/109368261/) uses the OF block to get the code (in a custom format) for rendering a given character:

![Example usage of OF block with dynamic variable name - pen text engine](https://user-images.githubusercontent.com/9948030/31551525-3a27707a-b00b-11e7-90e9-891cd664d9fb.png)

I've seen several pen text engines store character data this way. Here's [a project by CodeLegend](https://scratch.mit.edu/projects/118313394/) which stores character widths in variables, using them in a line wrapping procedure:

![Example usage of OF block with dynamic variable name - word wrapping procedure](https://user-images.githubusercontent.com/9948030/31551711-c516846e-b00b-11e7-984b-a310d4ea78fd.png)

---

The only trouble with ignoring variable IDs in the OF block (and instead looking up the variable by its name) is that, when a variable is renamed, OF blocks which simply contain the name of that variable would have to have their values changed (since their values would be a name, which is changed by rename, not an ID, which isn't changed).

/cc @tmickel since you helped with implementing the original attribute-of block.
