### ISSUE TITLE
Extensions should be able to define hidden blocks for compatibility

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#735]
### Expected Behavior

Because of changes in the set of blocks between 2.0 and 3.0, we need to provide support for compatibility with older projects. Part of this support involves the ability to define 2.0-compatible blocks that do not show up in the palette, but which can load in a project that uses them. 

### Actual Behavior

Extensions cannot yet define hidden blocks.

**Comment by towerofnix** [comment]
So, basically hacked blocks :)

I wonder if it would be better to transform old projects to use new, functionally equivalent blocks? That way there's no mysterious 2.0 "legacy" blocks floating around (which will inevitably be backpacked and used in new projects, because people love using hacked blocks).

**Comment by mrjacobbloom** [comment]
> I wonder if it would be better to transform old projects to use new, functionally equivalent blocks?

What about conversions to different ranges? It might be confusing to open an old project in Scratch 3.0 and see something like `change pen [color v] by ((variable) * (0.3922))`

**Comment by paulkaplan** [comment]
@cwillisf I see the `filter` property on blocks is designed to allow sprite/stage specific blocks. Do you think that could be used? Perhaps an empty array for "no targets"?
