### ISSUE TITLE
Investigate performance issues in "Sprite Caching Benchmark" project

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#744]
### Expected Behavior

- Project should run at 30fps on testing Chromebook

### Actual Behavior

- Project runs slowly

### Steps to Reproduce

https://scratch.mit.edu/projects/14844969/

**Comment by mzgoddard** [comment]
This project spends a lot of time in overhead with `execute` like https://github.com/LLK/scratch-vm/issues/740#issuecomment-341288496and #741 and `getProcedure*` calls like https://github.com/LLK/scratch-vm/issues/741#issuecomment-341532400. After those functions `needsConvexHullPoints` in `Drawable` is another contributor. `scratch-vm`'s isPromise spends a lot of time likely due to it being deoptimized like `execute`, especially with how simple a function it is.

## `needsConvexHullPoints`

`needsConvexHullPoints` is showing up a lot with how many calls to position changing block functions are made. It might not be `needsConvexHullPoints` itself but that the performance inspector sampled there frequently instead of other points spread out in functions `setXY` calls.

Improving `needsConvexHullPoints` and functions used by `setXY` more generally as it may need lots of small changes in logic order or variable assignment.

## `isPromise`

There are enough code blocks being executed to demonstrate the time isPromise uses. It'll likely become more obvious for other projects as the larger problems are solved. isPromise is getting enough different input types that javascript can't optimize it.

Looking at bluebird or other promise polyfills/implementations may show a good way to implement this function so it doesn't deoptimize.

## Some Numbers (MBP 13" 2013)

Here are the top operations and the part of a sample of 5 seconds of the project running.

operations | % of 5 seconds
--------|--------
indexOf | 14.0
execute | 13.7
getProcedureParamNames | 10.5
getProcedureDefinition | 5.8
stepThreads | 5.5
isPromise | 2.8

**Comment by thisandagain** [comment]
This project is now running at > 30 fps in the VM Playground on our testing hardware.
