### ISSUE TITLE
If_else enter loop when reporter is promise

### ISSUE THREAD

**Issue by felix2ch** [LLK/scratch-vm#824]
If_else block condition input from a promise reporter, It will run continually.

**Comment by thisandagain** [comment]
Hi @felix2ch, it is really hard to understand your issue. Can you please file a new issue and please fill out all of the fields in the template. In order to help we need:

- A clear description of the issue
- Steps to reproduce the issue if at all possible
- Information about your browser and operating system

**Comment by mrjacobbloom** [comment]
This sounds kind of like #464 but without more details that's just a shot in the dark
