### ISSUE TITLE
Pen project incompatibility

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-vm#855]
### Expected Behavior

_Please describe what should happen_
https://scratch.mit.edu/projects/113451797/#editor

### Actual Behavior

_Describe what actually happens_
https://llk.github.io/scratch-gui/develop/#113451797

![image](https://user-images.githubusercontent.com/654102/33898574-de14ea32-df36-11e7-8f95-b9635a70fbd3.png)

---

@ericrosenbaum I believe this is an issue with the translation of pen blocks into scratch 3. I assume that the brightness/saturation is set all the way down, and it isn't being reset correctly?

**Comment by towerofnix** [comment]
>I believe this is an issue with the translation of pen blocks into scratch 3. I assume that the brightness/saturation is set all the way down, and it isn't being reset correctly?

Probably - note that attaching blocks which set saturation and brightness make the program work:

!["set pen saturation" and "set pen brightness" placed before "set pen hue"](https://user-images.githubusercontent.com/9948030/33900715-606f34ee-df67-11e7-8a0d-e749187c4e19.png)

**Comment by thisandagain** [comment]
I was able to create a more minimal repro of this here:
https://llk.github.io/scratch-gui/develop/#192978361

The thing to note is "set the pen color to [white]" which causes the saturation and brightness values in the underlying pen state to be set in a way that is inconsistent with Scratch 2.0.

**Comment by thisandagain** [comment]
This points to a larger issue of the way we have "coupled" HSB together with the state of the color that is selected in Scratch 3.0. This is leading to this issue and needs some discussion to resolve.

**Comment by cwillisf** [comment]
Arright... I investigated this pretty thoroughly just now and here's what I found.

### Terminology

These color spaces have many names; I'll be using the same terms as the [Wikipedia article on HSL and HSV](https://en.wikipedia.org/wiki/HSL_and_HSV). In particular, I'll call these color spaces HSL and HSV (as opposed to, say, HSB). I'll refer to the components of the HSL color model as Hue, Saturation, and Lightness, and the components of the HSV color model as Hue, Saturation, and Value.

Note that hue is treated the same in HSL, HSV, Scratch 2.0, and Scratch 3.0 -- or, at least, that's the intent.

Instead of saturation and lightness/value, Scratch 2.0 has a "shade" component in its pen color model. This is the crux of the problem; more on this below.

In general I'll try to ignore range-mapping issues, such as the fact that HSV/HSL hue is generally treated as an angle in the range [0,360] or [0,360) while much of the Scratch code treats it as a [0,200) or [0,1]. I'll try to avoid talking about specific hue values (since they're mostly irrelevant to this issue) and for other values I'll try to talk about relative percentages rather than absolute values.

I'll also be referring to @thisandagain's example project, 192978361, and in particular the pen blocks used by that project. The project contains two "set pen color" blocks; for brevity and disambiguation I'll refer to "set color to {color picker}" as "set pen color" and "set color to {number}" as "set pen hue" -- this corresponds to the internal function names, anyway.

### Scratch 2.0 pen color model

The Scratch 2.0 pens color model is simplified: it's just hue and "shade" where the shade component affects both the saturation and lightness/value of the end result. Generally speaking, a shade value of 50% is a fully saturated "pure" hue, a shade value of 0% is always black, and a shade value of 100% is always white. (Did you feel that? It felt like foreshadowing...)

The Scratch 2.0 `set pen color` block sets both the hue and shade of the internal color model. First, it takes the RGB value from the eyedropper-selected color and converts it to HSV. Then, the pen hue is set to the HSV hue component and the pen shade is set to half the HSV value component. The saturation component of the HSV conversion is not used, but there's a comment in the Scratch 2.0 code suggesting that it should be used:
```as3
		penShade = 50 * hsv[2];  // not quite right; doesn't account for saturation
```

The Scratch 2.0 `set pen hue` block sets only the pen hue. The pen shade is unmodified by this block, meaning that saturation and lightness/value are held constant.

### Scratch 3.0 pen color model

Scratch 3.0 replaces the old 2-component model with a standard HSV representation. We still track pen "shade" for compatibility with the legacy `set pen shade to {number}` and `change pen shade by {number}` blocks, but shade is no longer treated as a primary component in most cases.

Unfortunately, because the saturation AND value components of the HSV representation are mixed into the shade value, it's not possible to have a clean round-trip conversion. In particular, white ends up with 0% saturation, where in the 2.0 system it would get a shade value of 50% which results in 100% saturation. Once saturation is at 0%, changing the hue will have no effect.

### Proposed solution

Let's take another look the Scratch 2.0 pen color model:
- 0% shade = black
- 50% shade = fully-saturated hue
- 100% shade = white

This doesn't sound like HSV to me. In fact, it looks like the outer shell of the [HSL chroma bicone](https://en.wikipedia.org/wiki/HSL_and_HSV#/media/File:HSL_color_solid_dblcone_chroma_gray.png)! That is, Scratch 2.0 pen colors correspond to the set of all HSL colors with 100% saturation.

My proposal is as follows:
- Adopt the HSL color model for the Scratch 3.0 pen (instead of HSV or hue+shade).
- Treat "shade" as HSL lightness.
- Bias saturation to 100% when it's compatible with user intent, such as in the initial pen state or when setting the pen color to white or black.
  - We'll have to think through all the cases -- IMO this is the only risky part of this plan. I'm not yet sure what would be best when setting the pen color to 90% gray, for example, but it feels like something that would have a mathematically-consistent "best" choice. Hopefully I/we/somebody can figure out what it is... 🤔💹
  - See also the [HSL cylinder](https://en.wikipedia.org/wiki/HSL_and_HSV#/media/File:HSL_color_solid_cylinder_alpha_lowgamma.png).
- New in Scratch 3.0: you can now get under the HSL chroma bicone's skin! That is, you can now set pen saturation to less than 100%.

I believe this is probably about half a day's work, unless setting saturation becomes a rabbit-hole. It may be safest to revert to a Scratch 2.0 color model for now and do some exploratory coding after the January milestone.

**Comment by thisandagain** [comment]
Amazing investigation and write-up as always @cwillisf. Can you, Paul, and Eric get together tomorrow to decide if it's worth to sink a half day in this or just revert as per discussion?

**Comment by paulkaplan** [comment]
I'm not sure about this. One problem is that using the eyedropper to set the pen color to any gray on the "inside" of the cone cannot be represented accurately by the scratch 2 model, so any project that does that and then changes hue/shade will have a behavior where the pen color first gets **pushed** out to the skin of the cone, then continues changing based on that new, representable, color. Projects that do things like set a color to white then change shade/hue (like andrews demo) wouldn't work in an HSL system either.

**Comment by cwillisf** [comment]
@paulkaplan and I just talked this through and found a very simple fix that doesn't require changing the color model. PR coming soon...
