### ISSUE TITLE
Pen colors are different in 3.0 than 2.0

### ISSUE THREAD

**Issue by BookOwl** [LLK/scratch-vm#887]
### Expected Behavior

The pen should handle colors the same in Scratch 3.0 as in Scratch 2.0

### Actual Behavior

In Scratch 3.0 the `set color to (number)` block doesn't work the same as it does in 2.0

### Steps to Reproduce

Run https://scratch.mit.edu/projects/196307621/ in the VM https://llk.github.io/scratch-gui/#196307621 . In Scratch 2.0 the circles are colored, in Scratch 3.0 the circles are all white.

### Operating System and Browser
Mac OS 10.11.6 Firefox 57.0.1

**Comment by towerofnix** [comment]
~~The problem seems to be that "set color to (number)" is being split into these two blocks here:~~ (see [below](https://github.com/LLK/scratch-vm/issues/887#issuecomment-355783490))

![Set pen color to white / set pen hue to color](https://user-images.githubusercontent.com/9948030/34643550-5a85ac72-f2fc-11e7-869c-3ba37d87819f.png)

If we look at the dropdown for "set pen color to (white)", we see that there's full brightness but zero saturation:

![Color: 0, Saturation: 0, Brightness: 100](https://user-images.githubusercontent.com/9948030/34643563-8aa300a8-f2fc-11e7-9b04-d1c373bf691c.png)

Thus "set pen hue" sets the correct "Color" value, but since saturation is zero, it still displays as white.

Editing the "set pen color" block to be deep red - that is, saturation 100 - fixes the problem.

Since the "set pen color to number" block is always split into a "set pen color to color" immediately followed by a "set pen hue to number", I think that simply making red (instead of white) be the color in the generated "set pen color to color" block would fix this?

**Comment by BookOwl** [comment]
@towerofnix, actually, _I_ added the "set pen color to (white)" block. I needed it in Scratch 2.0 to get the "set color to (number)" to actually change the color.

**Comment by paulkaplan** [comment]
I see those projects doing the same thing?

![pen-color](https://user-images.githubusercontent.com/654102/34744064-eb3c626a-f559-11e7-894d-c39d32eb6d1a.gif)

(p.s. you can use `/compatibility-testing.html#<project-id>` to see the side-by-side mode. note it only works only for public projects, and you may need to manually add the domain to the list of ok flash domains)

**Comment by BookOwl** [comment]
Well, it seems to be working now for me too. The GUI is a newer version than what I first tested it on though, so I guess that one of the recent commits must have fixed it.

**Comment by towerofnix** [comment]
>(p.s. you can use /compatibility-testing.html#<project-id> to see the side-by-side mode. note it only works only for public projects, and you may need to manually add the domain to the list of ok flash domains)

@paulkaplan Perhaps the compatibility-testing page should be mentioned at the start of the [Compatibility](https://github.com/LLK/scratch-vm/wiki/Compatibility) wiki page? That way people interested in seeing compatibility changes will be prompted to compare projects themselves (and of course, those people would probably be the ones most interested in testing compatibility).

**Comment by paulkaplan** [comment]
Great idea @towerofnix, I'll do that.
