### ISSUE TITLE
In sensing block "property of sprite", volume doesn't work

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#892]
### Expected Behavior

The sensing block "volume of sprite" should report the current volume of the sprite.

### Actual Behavior

The block does not report anything.

**Comment by ericrosenbaum** [comment]
This is a weird one, because the volume of a target is stored using custom state in Scratch3SoundBlocks. I can think of two ways to fix it, but not sure about either:

- Find a way for Scratch3SensingBlocks to access the custom state in Scratch3SoundBlocks. Not sure how this would work. It sort of breaks the model for custom state I think.

- Move the "volume" property out of custom state, and put it into RenderedTarget. Of course, the weird thing is, that class has properties that are used for rendering, not sound.

@cwillisf @rschamp any thoughts?

**Comment by cwillisf** [comment]
I can think of a third way, but it involves breaking some rules. We could theoretically make it so that an internal extension is allowed to put blocks in another category, so that the "volume of sprite" can be provided by the sound extension even though it shows up in the sensing category.

Assuming we don't do that, this could be solved in a few ways:
- The "volume of sprite" block could request the custom state corresponding to the sound blocks' key, and return a default value if it's not found.
- You could make a static method or freestanding function in the sound blocks package which the sensing blocks could `require` or `import` and then call. I think I'd prefer this one, since it centralizes the "get the custom state for sound if it's there" logic.

Either way, I'd stick with treating it as read-only for this case. In particular, if there is no sound-related custom state, I'd just returning a default volume without adding a sound-related custom state entry.
