### ISSUE TITLE
Clamping sound pitch effect

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#899]
### Expected Behavior

Executing blocks with valid inputs should most often have perceivable effects to the user.

### Actual Behavior

Setting the pitch to a really big negative number takes a long time to execute with no perceivable effect to the user.

The pitch effect should possibly be clamped to reasonable bounds so that effects can be perceived and code doesn't just seem to be hanging.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by ericrosenbaum** [comment]
Currently the pitch effect is clamped from -600 to 600. It is 120 steps per octave, so that's from -5 octaves to +5 octaves of pitch shifting. Maybe that's too much. :D

The issues at extreme parts of the range include:

- At extreme low values, you can't hear anything (mentioned above)
- At extreme low values, the sound is too long (also mentioned above). Pitch effect of -600 is shifted down 5 octaves, which will double the duration 5 times. So a sound that's 1 second long will last 32 seconds!
- At extreme high values, the sound can be become so short it's just a tiny click.
- At both high and low values, the sound becomes increasingly distorted (I think this is mostly interpolation and aliasing artifacts)

I did some experimenting with a variety of sounds, and I think a range of three octaves in either direction, -360 to 360, would work well. Generally, sounds are still audible at both -360 and 360, and the distortion is not terrible. At -360, the duration is doubled three times, so a 1 second sound lasts 8 seconds, which is long but not crazy.
