### ISSUE TITLE
"when timer > 0" hat + "reset timer" block doesn't make a loop

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-vm#906]
In 2.0, this runs forever after starting:
![image](https://user-images.githubusercontent.com/1512021/35123870-fc8e5112-fc71-11e7-9276-287e966421e3.png)

But in 3.0, it stops after a finite number of times.

**Comment by ktbee** [comment]
Whew! Got to the bottom of this one!

**The reason this doesn't work in Scratch 3:**

The "greater than" hat checks the timer for `timeElapsed` being greater than zero, and it never is because the "greater than" hat would need to check it when it's _exactly_ zero. Usually the closest it will get is something around 0.100. If you change the hat to check for "When timer > .1", the blocks will execute forever as in Scratch 2. 

Currently the hat's timer [gets the current time from the JavaScript's Date.now object](https://github.com/LLK/scratch-vm/blob/develop/src/util/timer.js#L58), which will continually update and prevent this current version of the hat from ever evaluating to false, which would prevent this edge-activated hat from [having its thread retired.](https://github.com/LLK/scratch-vm/blob/develop/src/engine/execute.js#L72-L75)

**The reason is _does_ work in Scratch 2:**

In Scratch 2, it's easier to have a timer's time elapsed value equal zero. The timer uses `currentMSecs` as its current time value, and that timestamp is mostly only updated [once per step of the Sequencer](https://github.com/LLK/scratch-flash/blob/72e4729b8189d11bbe51b6d94144b0a3c392ac9a/src/interpreter/Interpreter.as#L245) (though it can get updated in other circumstances as well). In addition to this timestamp not being updated as frequently as in Scratch 3, we found a race condition in Scratch 2 where [`currentMSecs` is updated _after_ edge triggered hats are processed.](https://github.com/LLK/scratch-flash/blob/develop/src/scratch/ScratchRuntime.as#L179-L180) This means these hats are effectively using the timestamp from the last step.

We're thinking about some possible solutions to this, but wanted to share our findings so far. Any thoughts on this are welcome :)

**Comment by ktbee** [comment]
Oh whoops, also meant to cc @thisandagain @kchadha

**Comment by kchadha** [comment]
@ktbee can this issue be fixed by having the `reset timer` block reset all the `when timer >` hats?

**Comment by mzgoddard** [comment]
@kchadha That won't match the behaviour Scratch 2 has. That would cause the threads to execute twice as often.

**Comment by ktbee** [comment]
I thought I'd post here [the fix that @mzgoddard and I came up with that is more compatible with Scratch 2's timer logic.](https://github.com/LLK/scratch-vm/compare/develop...ktbee:clock-timer-compat-fix?expand=1) However, @gnarf had a good question about whether we want to copy the  same Scratch logic or if we want to provide the same Scratch 2 behavior more systematically, perhaps by extending the hats API?
