### ISSUE TITLE
Figure out why push reported work is causing bugs

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-vm#929]
This is a follow up issue from #924 to figure out what is causing the regression from the push reported work. This work is being reverted in #928.

Below are examples of projects that fail due to this work, specifically [this commit](https://github.com/LLK/scratch-vm/commit/6b7582f1c70ce4f90a0ca5eb986d96771414d86b). 

https://llk.github.io/scratch-gui/develop/#10128407
https://llk.github.io/scratch-gui/develop/#10761768
https://llk.github.io/scratch-gui/develop/#56667360
https://llk.github.io/scratch-gui/develop/#21554369

**Comment by mzgoddard** [comment]
I found what was not working. Procedures and probably other blocks that pass booleans without a block like
![screen shot 2018-04-16 at 5 30 01 pm](https://user-images.githubusercontent.com/833298/38836402-01b35240-419c-11e8-9bb4-aec17df293bf.png)
return undefined from the empty boolean argument. This and some behaviour in the pushReported optimization caused procedures with undefined boolean arguments to get a reported value from another previously executed block. That value being truthy would case the procedure to behaviour differently.

The above example would pass 7 instead of undefined to the procedure call. One way to look at how this result came about may be that booleans don't have a shadow block or return false as a implied shadow value.

Fixing this in the pushReported optimization isn't going to be a lot of code. There is not a clear testing idiom though to test for another regression against this.
