### ISSUE TITLE
Pen Size Limit

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-vm#97]
_Does this belong in scratch-vm?_

In Scratch 2.0, pen size was limited to 255 due to a technical limitation of Flash (see [here](https://github.com/LLK/scratch-flash/blob/5cff62b909856b7d7b3d116a5dcc2b4f03de8482/src/scratch/ScratchSprite.as#L264)). This limit was not imposed in Scratch 1.4. Has any consideration been made as to whether this limit will remain in Scratch 3? The only real reason it could be desired is for backwards-compatibility. Is that reason enough to keep the limit?

---

Moved from LLK/scratch-blocks#552
/cc @PullJosh @pulljosh

**Comment by mrjacobbloom** [comment]
Another use case: I tried to re-create Agar.io in Scratch once, and for most characters I used one pen dot for each character, but for large characters I had to use a circle-drawing algorythm

**Comment by ed-cooper** [comment]
In built support for pen size > 255 should definitely be done - I've never seen a circle filler algorithm even come close to working at the speed of a single pen down and pen up.

As for backwards compatibility, I think the real question is are there actually any projects that take advantage of the limit? Because I can't find any

**Comment by CosmicWebServices** [comment]
Maybe the pen size cap should be at where it covers the full full screen with just one pen down if that make sense but that may differ for some browsers/computers.

**Comment by thisandagain** [comment]
I don't see any reason why this limit shouldn't be enough to cover the entire size of the stage.
